### ISSUE TITLE
[Problem] PartDesign Mirrored (It is impossible to leave only the mirrored part.)

### ISSUE THREAD

**Issue by free777cat** [realthunder/FreeCAD#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Linux Mint 22 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 2024.409.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 
  * FEMbyGEN 2.1.0
  * Sketcher
  * frame 0.1.1
  * Assembly4 0.50.6
  * mbdyn-dynamics
  * sheetmetal_середа, 10 квітня 2024.zip
  * fasteners 0.4.72
  * sheetmetal_субота, 06 квітня 2024.zip
  * sheetmetal.zip
  * lattice2 1.0.0
  * FEM_FrontISTR 0.1.0
  * sheetmetal_work_dxf.zip
  * sheetmetal_субота, 30 грудня 2023.zip
  * SheetMetalFoldCmd.py_повністю_робоча_неділя, 21 квітня 2024.zip
  * DynamicData 2.56.0
  * sheetmetal 0.4.13
  * Defeaturing 1.2.2
  * dxf-library
  * OpticsWorkbench 1.0.12
  * temp
  * ExplodedAssembly
[/code]
```

### Subproject(s) affected?

None

### Problem description

PartDesign Mirrored
It is impossible to leave only the mirrored part.

Only the mirrored part is needed for further actions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
![image](https://github.com/user-attachments/assets/14c5c1b9-3893-4d06-9305-78d660dddd65)

![image](https://github.com/user-attachments/assets/120d5a50-88ef-4d78-92db-b3b8b84f7738)

Please note that `HideBaseFeature` option will hide all previous features and leave only the new transformed feature, so it will produce the final result as shown below.

![image](https://github.com/user-attachments/assets/d99bfe11-1006-4517-8305-53c06005029d)

**Comment by free777cat** [comment]
Thank you!!!

**Comment by free777cat** [comment]
will this be pushed to the main FreeCAD branch?
