### ISSUE TITLE
Expression editor appears to float with no window background?

### ISSUE THREAD

**Issue by brandonbeaumia** [realthunder/FreeCAD#102]
Just installed the most recently daily AppImage (2021-02-05) and noticed this issue. I've tried changing my style sheets and the problem persisted. Pop_OS 20.04.

![Screenshot from 2021-02-06 19-49-42](https://user-images.githubusercontent.com/650565/107134091-7ddd7700-68b4-11eb-94cf-7fa0d92bf3bf.png)

**Comment by realthunder** [comment]
This is a feature actually. You can move and resize this edgeless dialog just the same by moving your mouse around the edge or top area. If you want the original normal dialog, uncheck `Preference -> Display -> UI -> Expression Editor -> In place edit`.

**Comment by brandonbeaumia** [comment]
OH! The look was so jarring I assumed there was something going wrong. I like that it pops up nearby, but the floating boxes look incredibly awkward. Glad that I can simply turn the feature off, thank you for pointing me in the right direction!
