### ISSUE TITLE
[Problem] invalid escape sequence: still present but only in the build procedure

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.41240 (Git)
Build type: Release
Branch: LinkMerge
Hash: bb0766acc3aa165bf2fc1b741a6d0217e5597df3
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.7.0
Locale: English/United States (en_US)
Installed mods: 
  * asm3 0.12.0
  * Assembly4 0.50.2
```
```


### Subproject(s) affected?

None

### Problem description

```
[ 13%] Generating version_check
/home/walter/Software/FreeCad/FreeCAD2/src/Tools/SubWCRev.py:269: SyntaxWarning: invalid escape sequence '\.'
  match = re.match("git@github\.com:(\S+?)/(\S+\.git)", url) or re.match(
/home/walter/Software/FreeCad/FreeCAD2/src/Tools/SubWCRev.py:270: SyntaxWarning: invalid escape sequence '\.'
  "https://github\.com/(\S+)/(\S+\.git)", url
/home/walter/Software/FreeCad/FreeCAD2/src/Tools/SubWCRev.py:274: SyntaxWarning: invalid escape sequence '\S'
  match = re.match("ssh://\S+?@(\S+)", url)
/home/walter/Software/FreeCad/FreeCAD2/src/Tools/SubWCRev.py:372: SyntaxWarning: invalid escape sequence '\*'
  if re.match("\*", self.branch) is not None:
git
/home/walter/Software/FreeCad/FreeCAD2/build/src/Build/Version.h.out written
[ 13%] Generating Version.h

```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
