### ISSUE TITLE
Workbench Path, in all versions, the problem of renaming operations

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#108]
![Снимок экрана от 2021-02-19 12-02-06](https://user-images.githubusercontent.com/18741088/108482772-fa0b8d80-72aa-11eb-9c74-6d39994aaa09.png)
The essence of the problem is that I create an operation. In the menu for creating an operation there is no possibility to set the name of the operation. Therefore, first the operation is created, and then we give it a name.
But in the code, g-code, it may not be reflected. It may or may not be reflected. The regularity is not revealed. There was a time when it seemed that the situation would be corrected after rearranging the operations, but this hypothesis proved to be wrong. It seemed that "close-open" file corrects the situation, but it is not true.
Not critical, but annoying.
On the screenshot you can see that on the left in the tree of operations each operation has a name, and on the right, in the window of the operation code, the name is not changed.

By the way - it would be just great if the code view window would be indented instead of colored formatting. 
![Снимок экрана от 2021-02-19 12-08-42](https://user-images.githubusercontent.com/18741088/108483018-48209100-72ab-11eb-97e6-cd1971d61821.png)

**Comment by snelweg** [comment]
Isn't this more of a Path WB problem?
The developer of the Path WB is very responsive and fixes errors quick. 
Brad Collette @sliptonic

**Comment by luzpaz** [comment]
@realthunder this ticket can be closed as it's not related to your branch.

**Comment by sliptonic** [comment]
I've reviewed this on FreeCAD master.  The output is generated in the postprocessor file.  OP didn't mention which post he's using but at least for LinuxCNC it is outputting the object Label not the name.  So if he changes name in the tree, it should be reflected in the postprocessed gcode.  Also recommend closing this here.  
OP if you still have an issue, post to the FreeCAD Path/CAM section of the forum

**Comment by luzpaz** [comment]
Thanks sliptonic. Closing ticked on your recommendation.

**Comment by tiket18** [comment]
The problem in the build of January 11 persists (checked in work yesterday). I can't use another version because of Python10.
As for the postprocessor issue. NO, no and no.
Indeed, if you go through a full cycle, ie means FC save g-code in the file, the names will be corrected, as well as removed K0 and speeds recalculated. BUT!!!
I do not do so, because FC requires manual control code, etc. I take the code from the Operation Viewer, each separately, or a general list from the Operation. So there the corrected names appear randomly. I create a dozen, name them all, then look at each one and copy it. Some of the names in the code have already changed, and some, all by Kozma Prutkov with a lion and an elephant - in the tree the name of the operation is one, and in the code - another.

**Comment by luzpaz** [comment]
>  OP if you still have an issue, post to the FreeCAD Path/CAM section of the forum  

@tiket18 :point_up: this is how you may get your Path issue addressed (note: sliptonic is the upstream Path WB main dev)
