### ISSUE TITLE
Copying of spreadsheets

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD#12]
Copying spreadsheets leads to not quite understandable errors for me.

Branch: LinkStage3 Commit: d03d5d66e1ddec6ea4aef88065906754cc788f87

[https://peertube.social/videos/watch/7315d6e4-d863-4292-8762-c0dcadf2d9de](Video)

![original](https://user-images.githubusercontent.com/6075465/56779773-e82c4100-681f-11e9-878d-48d983a6c47f.png)
![copy](https://user-images.githubusercontent.com/6075465/56779778-e9f60480-681f-11e9-841a-9d2faf1b2776.png)

**Comment by realthunder** [comment]
Please sync with my branch and try again. If there is still problem, please prepare a small file to demo the problem.

**Comment by yrabbit** [comment]
After sync, everything works as it should. Thanks.
