### ISSUE TITLE
Can't remove constraint in any sketch 

### ISSUE THREAD

**Issue by AcumenDev** [realthunder/FreeCAD#123]
How repeat:
Create new document, create new sketch, draw line and create any constraint. Now can't you remove this constraint.

OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.328.22506 +5276 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ff1590e1d7c0aeaf45a29941ec20a10d54cf92ff
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
****

**Comment by luzpaz** [comment]
Closing. If @AcumenDev can reproduce, they're welcome to reopen.
