### ISSUE TITLE
Subtractive Loft returns error in any..

### ISSUE THREAD

**Issue by projectcad** [realthunder/FreeCAD#129]
Subtractive Loft returns error in any ..![subtractiveLoft](https://user-images.githubusercontent.com/68682837/115147830-9cef4680-a065-11eb-975c-b8d2fd2b14db.png)

**Comment by realthunder** [comment]
From the screenshot, it seems you've selected the 'Pad' as the profile? By right, you should select one of the sketch as profile. Can you please provide the file to confirm?

**Comment by projectcad** [comment]
Yeah..you are absolutely right..my fault..i misunderstood "Subtractive Loft" command   due to another smilar command 's flow ...my apologies...

**Comment by projectcad** [comment]
Yeah..you are absolutely right..my fault..i misunderstood "Subtractive Loft" command due to another smilar command 's flow ...my apologies...
