### ISSUE TITLE
Failed to restore #Assembly: Null input shape

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD#13]
Hello
I can not load the assembly with only one part. Is this how it should be?
Branch: LinkStage3  Commit:0e5785966a316dd81d7f4a102413dcb507627449

[cube.zip](https://github.com/realthunder/FreeCAD/files/3169772/cube.zip)
![null-shape](https://user-images.githubusercontent.com/6075465/57578293-af04f980-74cc-11e9-884e-3384c0ff99c4.gif)

**Comment by realthunder** [comment]
Should be fixed. Please check.

**Comment by yrabbit** [comment]
Thanks! It works now.
