### ISSUE TITLE
Step file origin gone after importing

### ISSUE THREAD

**Issue by ghost** [realthunder/FreeCAD#130]
Importing a step file with:
Version: 2021.412.22506 +5327 (Git) AppImage
Build type: Release
Branch: LinkDaily

![link-daily-import](https://user-images.githubusercontent.com/14362636/115710294-cc3cd680-a337-11eb-9de0-3788ad546d77.png)

Importing same step file with:
Version 0.20, Revision number 24720

![version-20-import](https://user-images.githubusercontent.com/14362636/115710608-2ccc1380-a338-11eb-9af8-d8d658c6db8e.png)

Lack of origin causes errors if you move from your LinkDaily back to the official version.

**Comment by realthunder** [comment]
I'll add an option to force create origin in App::Part. Meanwhile you can use the following python code (using my branch) to do just that (explanation: the origin object will auto create the missing origins if there is any code accessing them).

```python
for obj in App.ActiveDocument.Objects:
  if obj.isDerivedFrom('App::Origin'):
    _ = obj.OriginFeatures
```

**Comment by realthunder** [comment]
Oh, forgot about that. There is already a parameter controlling this behavior. Boolean parameter named `CreateOrigin` in path `BaseApp/Preference/Group`. Create this parameter if it's not there and set it to `True`.

**Comment by ghost** [comment]
I added CreateOrigin and it worked fine.

Thanks

**Comment by luzpaz** [comment]
@realthunder good to close, right?
