### ISSUE TITLE
The problem of the topology of body naming

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#136]
I believe this is it. It shows up in the last build of April 30 and in all previous builds.
There is a part, there are grooves in it. If we open the groove sketch and put one of the grooves in the "auxiliary geometry" category (i.e. so that this fragment of the sketch takes no part in shaping the groove) = the next "layer" (stage) breaks down. File step1 is before this change.

The file itself - traditionally, by mail.

![Снимок экрана от 2021-05-02 18-17-17](https://user-images.githubusercontent.com/18741088/116818307-6dffc700-ab73-11eb-80d1-a8a4bb28a1d9.png)
![Снимок экрана от 2021-05-02 18-17-02](https://user-images.githubusercontent.com/18741088/116818310-6f30f400-ab73-11eb-973a-5210ece047ec.png)
![Снимок экрана от 2021-05-02 18-16-37](https://user-images.githubusercontent.com/18741088/116818311-6f30f400-ab73-11eb-89c6-d3031098b7cf.png)

**Comment by realthunder** [comment]
Forgot to reference this issue, but it is fixed by commits 753a2763186d99db8c38ebf34882d8ba29e517ad and 41270e9d2dfedefa93bc12bf99e4ef7a0d8960a8.

This is indeed a topo naming problem and is quite serious. Thanks for reporting.
