### ISSUE TITLE
Conda build on macOS tests fail

### ISSUE THREAD

**Issue by vectronic** [realthunder/FreeCAD#14]
Hello there,

I have previously successfully built the upstream codebase on macOS using Conda. I detail the steps I followed here: 

https://vectronic.io/posts/building-freecad-with-3dconnexion-support-on-macos-using-conda/

I have applied the same steps to this fork using:

git_url = https://github.com/realthunder/FreeCAD.git
version = 4f76634

This is the version you released a few days ago.

I just wanted to report that the Conda package builds ok but then the automated tests fail. 

However I did still manage to get the Conda package installed and then followed slightly tweaked instructions for installing the Assembly workbench and SolveSpace.

It seems to behave pretty much as the pre-built binary you provided (apart from the fact my build is done with support for 3D Connexion input device which is what I was chasing).

If you want to know any further details on which tests failed let me know (but you might need to tell me what to log/attach etc. because the internal build/test workings of FreeCad are still foreign to me...).

Thanks for the good work!

**Comment by realthunder** [comment]
Thanks for the appreciation.

Actually, your blog post sits in my browser tab list for quite some time already. Just didn't have time to try that yet.  And yes, there is some problem with the conda test part. I also disabled it when building for Linux. I'll investigate it later.

**Comment by vectronic** [comment]
FYI: A repeatable (hopefully) guide for Assembly3 Conda build on macOS: https://vectronic.io/posts/building-freecad-assembly3-on-macos-using-conda/

**Comment by luzpaz** [comment]
@realthunder I'm closing this ticket
