### ISSUE TITLE
PATH GUI workbench

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#140]
Recently, when you set additional options (dressup) for a tool path, the GUI window started to open (and it's a good thing) to specify the necessary parameters. However, all the parameters do not fit on the screen, and there is no possibility to expand, zoom or shift them. Shall I make it wider? = please. But by height - no. This is an error.
![Снимок экрана от 2021-05-05 19-30-58](https://user-images.githubusercontent.com/18741088/117176773-ec10d780-add8-11eb-8629-d3c5a3142320.png)

**Comment by luzpaz** [comment]
Not enough info given. Closing
