### ISSUE TITLE
Ubuntu 18.04 building failed..

### ISSUE THREAD

**Issue by projectcad** [realthunder/FreeCAD#145]
Please be informed that after updating linkstage3 of today...it returns error like below while building..
![LinkStage3BuildError](https://user-images.githubusercontent.com/68682837/118163867-24dd2c00-b42b-11eb-8f6c-7b8cc407fb85.png)

**Comment by realthunder** [comment]
Can please find and delete the file EditDatumDialog.cpp.o and try make again?

**Comment by projectcad** [comment]
Thanks.. Building is OK..
but this time, another error like below while installing with "sudo make install"
![LinkStage3Build2](https://user-images.githubusercontent.com/68682837/118253323-7b417d80-b4b2-11eb-9570-6e2da748bb3f.png)

**Comment by realthunder** [comment]
Well, I guess you'll have to find and delete `MeshPartGui.so` in your build directory (note, not `/usr/local/lib`), and `make install` again. I think there is some problem with Linux parallel make. Maybe some race condition somewhere.

**Comment by projectcad** [comment]
👍Finally OK...
after deleting MeshPartGui.so 
i tried building  and installing again..
no any error at both of them.. moreover, no any problem at EditDatumDialog.cpp.o and MeshPartGui.so (before deleting them, their sizes are 0...)
