### ISSUE TITLE
Unable to select the vertices of the rectagle I just created.

### ISSUE THREAD

**Issue by bassamanator** [realthunder/FreeCAD#148]
Hi there,

I created a plane, selected the plane, hit create sketch, created a rectangle and was unable to select the vertices of the rectangle. Tried zooming in, flipped over to the other side...nothing worked. This has happened before. I immediately switched over to the official version of Freecad and was able to select the vertices.

Here's a [clip](https://drive.google.com/file/d/1kdtclO8xgt6s1HHhkyNmhWnDSs9FHVwz/view?usp=sharing) of this. 

Absolutely love the Link Branch!

>OS: Manjaro Linux (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.504.24301 +3511 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: b8cd87c34a66a8f7a8177f483cebf79e29273813
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/Canada (en_CA)

**Comment by realthunder** [comment]
Hi, this problem has been solved in the latest release. Please try.

**Comment by luzpaz** [comment]
@bassamanator i'm closing this ticket. If you can reproduce please re-open
