### ISSUE TITLE
Compiling of LinkDaily Branch returns error at Mesh.dir

### ISSUE THREAD

**Issue by projectcad** [realthunder/FreeCAD#150]
Compiling of LinkDaily branch returns error...i tried also "make" command with single core..but same error
![linkdaily1](https://user-images.githubusercontent.com/68682837/120917510-5fe41f80-c6b8-11eb-8f07-6e87496d79f4.png)
![linkdaily2](https://user-images.githubusercontent.com/68682837/120917518-670b2d80-c6b8-11eb-8b73-76bd43aeca74.png)
![linkdaily3](https://user-images.githubusercontent.com/68682837/120917521-683c5a80-c6b8-11eb-9ab6-605e51ace650.png)
![linkdaily4](https://user-images.githubusercontent.com/68682837/120917524-683c5a80-c6b8-11eb-9e4f-3e19092e2a17.png)
![linkdaily5](https://user-images.githubusercontent.com/68682837/120917525-68d4f100-c6b8-11eb-9fc1-4d974bc07257.png)

**Comment by realthunder** [comment]
The error doesn't make much sense. Probably another weird problem caused by parallel build. Please manually delete the `Mod/Mesh` directory in your **build** directory and try again.

**Comment by projectcad** [comment]
Thanks..it is OK after deleting Mesh dir...but very interesting that paralel compiling causes error only at Mesh...no any error at others..

**Comment by projectcad** [comment]
Updated and then tried to compile with paralel cores today...no any error this time..
