### ISSUE TITLE
Changing pad value does not show change in display.

### ISSUE THREAD

**Issue by ghost** [realthunder/FreeCAD#154]
See attached file rod.FCStd (renamed rod.zip)
[rod.zip](https://github.com/realthunder/FreeCAD/files/6719296/rod.zip)

Change the pad length from 400 to 500 and there will be no change in the part on the screen (the length green highlight box will change).

This happens on
OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

I opened the same file with
OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.20.25131 (Git) AppImage
Build type: Release
Branch: master
Hash: 7c519689f0d5ea78fb3292be36a857d283c05507
Python version: 3.9.5
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

and the part changed as expected.

**Comment by luzpaz** [comment]
Closing ticket
