### ISSUE TITLE
Windows 10 build fails. No boost lib found

### ISSUE THREAD

**Issue by Kuzma30** [realthunder/FreeCAD#159]
When I try to configure with Cmake 3.8.2 I get such error
https://pastebin.com/czxQNBNj

I use FreeCADLibs_asm3_12.5.5_x64_VC17.7z and latest daily branch.

**Comment by realthunder** [comment]
I can't access the pastebin link (404 error). Can please you post again?

**Comment by Kuzma30** [comment]
https://pastebin.com/A56NaA1t

**Comment by Kuzma30** [comment]
https://pastebin.pl/view/885e6d4e

**Comment by realthunder** [comment]
What is your cmake command? It looks like you didn't specify the libpack directory. This is mine.

```bat
cmake -G "Visual Studio 16 2019" -A  x64 ^
            -DFREECAD_LIBPACK_DIR="%libpackpath%" ^
            -DFREECAD_USE_PYBIND11:BOOL=ON ^
            -DBUILD_FLAT_MESH:BOOL=ON ^
            -DBUILD_FEM_NETGEN:BOOL=ON ^
            -DOCC_INCLUDE_DIR="%libpackpath%/include/opencascade" ^
            -DPYTHON_EXECUTABLE="%libpackpath%/bin/python.exe" ^
            ..
```

**Comment by Kuzma30** [comment]
Run cmake with your command
https://pastebin.pl/view/e3922c7e

**Comment by realthunder** [comment]
I didn't have `-DBOOST_LIBRARYDIR` argument. Also, please use a newer cmake. I am using 3.14.5.

**Comment by Kuzma30** [comment]
I now use latest cmake, it configure fine. Thanks.

**Comment by luzpaz** [comment]
@Kuzma30 pls close ticket

**Comment by realthunder** [comment]
@luzpaz I have just added you as the collaborator of this repo. Did you get the invitation?
