### ISSUE TITLE
Save/Load job error

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD#17]
Hello,
I can't load file with simple job:
Branch: LinkStage3 Commit:fc71c1b8b0e0729d7c6b8e4dcfa9cf7642ad7c5e

![job](https://user-images.githubusercontent.com/6075465/64315287-f3c11d00-cff4-11e9-9a1b-582f1bf76cf5.gif)

**Comment by realthunder** [comment]
I am currently on holiday, and will be back on 15th. Maybe you can revert to some early revision and try. I recently did a lot of cherry picks from LinkMerge branch. Probably messed up in some commit.

**Comment by realthunder** [comment]
Should be fixed.
