### ISSUE TITLE
LinkDaily build fails on ubuntu 20.04

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#173]
While LinkStage3 was successfully built on the same machine (ubuntu 20.04) without problems, the compilation of LinkDaily terminated with the following error message:

Scanning dependencies of target PathGui
[ 89%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/qrc_Path.cpp.o
[ 89%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/Command.cpp.o
[ 89%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/AppPathGui.cpp.o
[ 89%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/AppPathGuiPy.cpp.o
[ 89%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/PreCompiled.cpp.o
[ 89%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/DlgSettingsPathColor.cpp.o
/home/walter/Software/FreeCad/FreeCAD/src/Mod/Path/Gui/DlgSettingsPathColor.cpp:101:10: fatal error: moc_DlgSettingsPathColor.cpp: No such file or directory
101 | #include "moc_DlgSettingsPathColor.cpp"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by realthunder** [comment]
This problem has been solved recently. Please sync the branch and try again.

**Comment by wsteffe** [comment]
OK. Synced and successfully built.  Problem solved.
