### ISSUE TITLE
Navigation cude characters size.

### ISSUE THREAD

**Issue by onekk** [realthunder/FreeCAD#177]
How to modify the Navigation Cube character size, they are almost unreadable, see image:

![ls3-nav](https://user-images.githubusercontent.com/7129964/132882750-a44722b9-d97e-45ec-af3b-364b357aa701.png)

This is my version info

OS: Artix Linux (openbox)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3627 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: f63a5ea7b459872a3798027df0ff25e776524859
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: Italian/Italy (it_IT)

I have installed the stock FreeCAD appimage and everything is fine.

Regards

Carlo D.

**Comment by bambukouk** [comment]
Have you tried cube menu addon?

**Comment by wohltat** [comment]
I've tried the cube menu addon but i can't see any new settings. Of course i did a FC restart. Am i missing something here?
![image](https://user-images.githubusercontent.com/4751351/133618753-334c2db6-f7d2-4207-8bf8-cd4ca17f7224.png)

It seems as it should be possible to change the font size with the cube menu addon.
https://forum.freecadweb.org/viewtopic.php?f=34&t=43338&start=10#p379761

Nevertheless, i think the cube should work out of the box. The font size is even a bit small on my system but @onekk s cube font looks really tiny which i would consider a bug.

-------
```
OS: Linux Mint 20.1 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```

**Comment by realthunder** [comment]
Please try the latest 09.16 release.

![navi-cube](https://user-images.githubusercontent.com/1207888/133620896-5ae35b8d-d7d8-449c-b37e-380b6ae0e2e2.gif)

**Comment by wohltat** [comment]
Great. Works like in the video, so there is no need for the addon anymore.

**Comment by bambukouk** [comment]
Proper job :+1:  
Works a treat - another addon gone ...

**Comment by onekk** [comment]
I can confirm that the new version 20210916 (Stable) Improve the character size, and permit to change directly using the "small navigation cube", but the "predefined view icons" are disappeared.

There is a way to having them back?

Regards

Carlo D.

**Comment by bambukouk** [comment]
Also, if one changes to either orthographic or perspective view than it seems impossible to get back to isometric view.
One can toggle between orto and perspective but no way to get back to iso?

**Comment by bambukouk** [comment]
> .... but the "predefined view icons" are disappeared..

no, they just moved on - right click anywhere on the screen:

![right click](https://user-images.githubusercontent.com/50301871/133897479-504eff7e-08ae-485a-b8b0-edf9d792ff56.jpg)

**Comment by luzpaz** [comment]
Ticket looks like it can be closed.
