### ISSUE TITLE
Build fails on Debian 10

### ISSUE THREAD

**Issue by macdroid53** [realthunder/FreeCAD#179]
As requested on Discord.

These files were produced today after a git pull with the following commands:

`git pull
 cd ../freecadL3-build
 cmake -DBUILD_QT5=ON  -DPYTHON_EXECUTABLE=/usr/bin/python3 ../freecadL3-source
 make -j5
`

For a final build I'd probably add: -DCMAKE_BUILD_TYPE=Release
(is this necessary or not...?)

[CMakeError.log](https://github.com/realthunder/FreeCAD/files/7169871/CMakeError.log)
[CMakeCache.txt](https://github.com/realthunder/FreeCAD/files/7169896/CMakeCache.txt)

**Comment by ceremcem** [comment]
FYI: You can also consider using the automatic builder scripts: https://github.com/ceremcem/build-freecad-asm3 

Exact compilation command is here: 

https://github.com/ceremcem/build-freecad-asm3/blob/e58d60f460c97be3a7b81c6ea173d58de07b74a7/build-fc.sh#L137-L143

**Comment by realthunder** [comment]
Couldn't find any clue from the attached files. Maybe you can try the cmake command below for luck, which is basically what I use. Or, try ceremcem's script above.

```
cmake \
    -DOCCT_CMAKE_FALLBACK=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DFREECAD_USE_OCC_VARIANT="Official Version" \
    -DBUILD_QT5:BOOL=ON \
    -DUSE_BOOST_PYTHON:BOOL=OFF \
    -DFREECAD_USE_PYBIND11:BOOL=ON \
    -DBUILD_ENABLE_CXX11:BOOL=ON \
    -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
    -DBUILD_PLOT:BOOL=OFF \
    -DBUILD_SHIP:BOOL=OFF \
    -DFREECAD_USE_QT_DIALOG:BOOL=ON \
    -DBoost_NO_BOOST_CMAKE:BOOL=ON \
    -DFREECAD_USE_QWEBKIT:BOOL=ON \
    -DBUILD_FLAT_MESH:BOOL=ON \
    ..
```

**Comment by macdroid53** [comment]
I really hesitate to use the script described by ceremcem, it seems like adding another layer of things that can go wrong, and it adds some sort of container?? (which again, seems like more possible points of breakage.)

I created a new clone from git.

I then issued the following while in the freecadL3-build diretory:
`cmake     -DOCCT_CMAKE_FALLBACK=1     -DCMAKE_BUILD_TYPE=Release     -DFREECAD_USE_OCC_VARIANT="Official Version"     -DBUILD_QT5:BOOL=ON     -DUSE_BOOST_PYTHON:BOOL=OFF     -DFREECAD_USE_PYBIND11:BOOL=ON     -DBUILD_ENABLE_CXX11:BOOL=ON     -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3     -DBUILD_PLOT:BOOL=OFF     -DBUILD_SHIP:BOOL=OFF     -DFREECAD_USE_QT_DIALOG:BOOL=ON     -DBoost_NO_BOOST_CMAKE:BOOL=ON     -DFREECAD_USE_QWEBKIT:BOOL=ON     -DBUILD_FLAT_MESH:BOOL=ON ../freecadL3-source
`

This resulted in the following:

`-- Found PythonInterp: /usr/bin/python3 (found version "3.7.3") 
-- Found PythonLibs: /usr/local/lib/libpython3.7m.a (found suitable exact version "3.7.3") 
CMake Error at cMake/FreeCAD_Helpers/SetupPybind11.cmake:7 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:47 (SetupPybind11)


-- Configuring incomplete, errors occurred!
See also "/home/mac/freecadL3-build/CMakeFiles/CMakeOutput.log".
`

[CMakeOutput.log](https://github.com/realthunder/FreeCAD/files/7178430/CMakeOutput.log)

**Comment by wohltat** [comment]
> I really hesitate to use the script described by ceremcem, it seems like adding another layer of things that can go wrong, and it adds some sort of container?? (which again, seems like more possible points of breakage.)

Maybe look at it that way, your configuration is broken already. This gets more likely the more different a system becomes from the original developers machine. The script by ceremcem creates a kind of virtual machine that is the same everywhere so there is actually less that can go wrong in a way.

I also had a lot of problems compiling and found ceremcems solution very helpful. In my experience the compilation is pretty easy. But i also have to admit that it is not exaclty the same as if you would compile it on your system directly. Because it is inside the container, you have to do some additional stuff to run it outside the vm and to use your settings.  
I haven't used the script for a while but, as far as i remember it is documented or there are even some helper scripts present.

**Comment by macdroid53** [comment]
I appreciate what you say. But, I don't concede my configuration is broken.

I routinely use the process described in the wiki to compile the master, each day, on Debian 10, 11, UbuntuStudio 20.04, and Raspberry Pi.

Ok, so maybe from the linkdaily point of view, the configuration is broken.

What makes the linkdaily so special? I mean, after all...the readme points to the same build instruction wiki...

If those instructions are so wrong as to need 3rd party scripts...hmm.

**Comment by realthunder** [comment]
My branch last synced with FreeCAD 0.19.2 in this March. I hardly changed any `CMakeList` file. They should have the exact same dependency requirement.

Anway, according to your cmake output, you are missing `pybind11` dependency as requested in the cmake command. `pybind` is not a mandatory dependency, but since my cmake command asked for it, just install it  with `sudo apt-get pybind11-dev`.

**Comment by macdroid53** [comment]
I thought that was there. I'll check and try again tomorrow. 

Thanks!

**Comment by macdroid53** [comment]
Well, I added pybind11-dev. Still crashes at the same origin point in the make.

It appears there is something about Debian 10 just isn't right to build this branch.

The error (which I think is the original I got) is:

`Linking C executable cmTC_e4e55
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e4e55.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_e4e55.dir/CheckFunctionExists.c.o  -o cmTC_e4e55 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_e4e55.dir/build.make:87: cmTC_e4e55] Error 1
make[1]: Leaving directory '/home/mac/freecadL3-build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_e4e55/fast] Error 2
`

"cannot find -lpthreads" seems to be the issue, but, I've not found a clear idea of what is needed to correct this.

Since you say the dependencies are the same as the master and the master builds fine, I'm at loss.

**Comment by realthunder** [comment]
Can you please clear your build directory, and run the cmake command again and save its complete output and post it here?

**Comment by macdroid53** [comment]
Ok, starting with ~/freecadL3-build empty.

Used the following cmake command:

`cmake     -DOCCT_CMAKE_FALLBACK=1     -DCMAKE_BUILD_TYPE=Release     -DFREECAD_USE_OCC_VARIANT="Official Version"     -DBUILD_QT5:BOOL=ON     -DUSE_BOOST_PYTHON:BOOL=OFF     -DFREECAD_USE_PYBIND11:BOOL=ON     -DBUILD_ENABLE_CXX11:BOOL=ON     -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3     -DBUILD_PLOT:BOOL=OFF     -DBUILD_SHIP:BOOL=OFF     -DFREECAD_USE_QT_DIALOG:BOOL=ON     -DBoost_NO_BOOST_CMAKE:BOOL=ON     -DFREECAD_USE_QWEBKIT:BOOL=ON     -DBUILD_FLAT_MESH:BOOL=ON ../freecadL3-source > ~/cmakecapture.txt`

This produced the following output:

`-------------------------------------------------
Doxygen not found, will not build documentation.     
-------------------------------------------------
-------------------------------------------------
Now run 'cmake --build /home/mac/freecadL3-build' to build FreeCAD
-------------------------------------------------
`

And the captured output: 
[cmakecapture.txt](https://github.com/realthunder/FreeCAD/files/7186595/cmakecapture.txt)

**Comment by ceremcem** [comment]
> I haven't used the script for a while but, as far as i remember it is documented or there are even some helper scripts present.

@wohltat I've made many improvements since then and currently whole setup is performed from scratch by only: 

```
git clone https://github.com/ceremcem/build-freecad-asm3
cd build-freecad-asm3/tools
./auto.sh [--freecad-src /path/to/existing/FreeCAD]
# after compilation finished
./freecad.sh
```


@macdroid53 These idea behind these scripts exactly satisfies the issues you described. Behind the scenes, an LXC container is set up and FreeCAD source code is copied or cloned inside it, dependencies are installed and compilation is started. 

You can directly make use of those scripts by skipping the virtual machine part, because I already use Debian 10 for that virtual environment. That means you must perfectly be able to use those scripts inside a Debian 10 host machine.

Also, there is **no performance penalty** of using an application inside a "container" because we are using `chroot` behind the scenes. 

Choice is, of course, yours.

**Comment by realthunder** [comment]
That's strange. According to the output, cmake completes without error? And you can't run make?

**Comment by ceremcem** [comment]
@macdroid53 Hopefully you can initiate your setup directly on your Debian 10 host by: 

```
git clone https://github.com/ceremcem/build-freecad-asm3
cd build-freecad-asm3
./install-fc-deps.sh || dpkg --configure -a
./build-fc.sh
# after compilation ends, run FreeCAD by: 
~/fc-build/Release/bin/FreeCAD
```

Note that: 
* Scripts expect a FreeCAD git repo at `~/FreeCAD`
* Scripts create a `~/fc-build` directory

**Comment by macdroid53** [comment]
> That's strange. According to the output, cmake completes without error? And you can't run make?

With this command: make -j5 >~/makecapture.txt

Produces this capture:
[makecapture.txt](https://github.com/realthunder/FreeCAD/files/7186716/makecapture.txt)

And this at the terminal:
[maketerminalcapture.txt](https://github.com/realthunder/FreeCAD/files/7186720/maketerminalcapture.txt)

**Comment by macdroid53** [comment]
> @macdroid53 Hopefully you can initiate your setup directly on your Debian 10 host by:
...

I appreciate what you are saying and your help.

But, I don't understand why your scripts will work and the default process won't?

If there are dependencies missing, then why does a default build of master find them and not find them the linkdaily fork?
Why will your scripts find them and but, the default build instructions don't, given the same machine?

**Comment by ceremcem** [comment]
If I were you and I still wonder the answers of those questions, my debug session would follow those steps: 

1. Run `./install-fc-deps.sh || dpkg --configure -a` and then retry your own way of building. If it succeeds, then you are missing some dependencies. If you still fail to compile, then proceed to step 2. 
2. Run `./build-fc.sh`. If it succeeds, then you are issuing some commands in a wrong way. Print the exact compilation command as I mentioned [here](https://github.com/realthunder/FreeCAD/issues/179#issuecomment-920010259). 
3. If my whole "host" procedure fails, then run the original command (`./auto.sh`) and try installing inside a container. If it succeeds, then it means you have some issues in your host environment.

**Comment by macdroid53** [comment]
> If I were you and I still wonder the answers of those questions, my debug session would follow those steps:
> 
>     1. Run `./install-fc-deps.sh || dpkg --configure -a` and then retry your own way of building. If it succeeds, then you are missing some dependencies. If you still fail to compile, then proceed to step 2.

Succeeding to build would imply that your script knows some secret sauce, not mentioned in the documentation for building the linkdaily.
And, If it succeeds, I fully expect, the next time I attempt to build master, that it will fail...but, I'm probably just paranoid. :)

> 
>     2. Run `./build-fc.sh`. If it succeeds, then you are issuing some commands in a wrong way. Print the exact compilation command as I mentioned [here](https://github.com/realthunder/FreeCAD/issues/179#issuecomment-920010259).

I have shown the various commands I've attempted previously. The link shows a clip of a larger script, with arguments being added by the input of the script. Necessary, superfluous...? And, the command as shown there is a subset of what realthunder uses. So, that is better? Why?

> 
>     3. If my whole "host" procedure fails, then run the original command (`./auto.sh`) and try installing inside a container. If it succeeds, then it means you have some issues in your host environment.

I have a PC running Debian 10, I've added the dependencies, as specified by documentation. I read this and it seems there is a virtual environment involved, that I have not. (Or, your process creates some sort of container (like an appimage?) 

I'm sorry if I seem to ask a lot of questions or appear argumentative. I probably can't see the whole picture and am timid about adding another variable to the fray.

**Comment by ceremcem** [comment]
@macdroid53 I just wanted to forget everything about the build process, so I wrote those scripts. I can't really remember where I collected all the information for building FreeCAD Assembly3. Your questions are completely okay for me, there is no problem. 

Those scripts are the exact build documentation, in fact. You can execute them step by step and find out the actual problem you are having on your host. 

> I have a PC running Debian 10, I've added the dependencies, as specified by documentation. 

Can you please cross check the dependencies you have installed with my [packages.txt](https://github.com/ceremcem/build-freecad-asm3/blob/e58d60f460c97be3a7b81c6ea173d58de07b74a7/packages.txt)? Are there any differences?

**Comment by realthunder** [comment]
> With this command: make -j5 >~/makecapture.txt

Based on the make output, the problem is that `cmake` found the wrong python library, which can be seen in the previous cmake output capture below. It is trying to use a static linked library (libpythonXXX.a), while FreeCAD requires a shared library (libpythonXXX.so).

```
-- Found PythonInterp: /usr/bin/python3 (found version "3.7.3") 
-- Found PythonLibs: /usr/local/lib/libpython3.7m.a (found suitable exact version "3.7.3") 
-- Found PythonLibs: /usr/local/lib/libpython3.7m.a
```

You said you've managed to compile upstream FreeCAD before. Can you please dig up the CMakeCache.txt there and post it here. I'll check which Python library you were using when building upstream.

**Comment by macdroid53** [comment]
> You said you've managed to compile upstream FreeCAD before. Can you please dig up the CMakeCache.txt there and post it here. I'll check which Python library you were using when building upstream.


[CMakeCache.txt](https://github.com/realthunder/FreeCAD/files/7189847/CMakeCache.txt)

**Comment by macdroid53** [comment]
> @macdroid53 I just wanted to forget everything about the build process, so I wrote those scripts. I can't really remember where I collected all the information for building FreeCAD Assembly3. Your questions are completely okay for me, there is no problem.
> 
> Those scripts are the exact build documentation, in fact. You can execute them step by step and find out the actual problem you are having on your host.
> 
> > I have a PC running Debian 10, I've added the dependencies, as specified by documentation.
> 
> Can you please cross check the dependencies you have installed with my [packages.txt](https://github.com/ceremcem/build-freecad-asm3/blob/e58d60f460c97be3a7b81c6ea173d58de07b74a7/packages.txt)? Are there any differences?

The base list is identical, but you add these:

```
# FCCamera Macro
PySide2.QtXml

# FEM
netgen
netgen-headers
libmetis-dev
calculix-ccx
gmsh
```

**Comment by realthunder** [comment]
According to your latest CMakeCache.txt, you are using `/usr/local/bin/python3` instead of `/usr/bin/python3` when compiling upstream. Apparently you have two variant of Python3 installed for some reason. The `/usr/bin/python3` is not usable for FreeCAD. So just replace that in the camke command and try again. Be sure to clear your build directory first.

```
cmake -DOCCT_CMAKE_FALLBACK=1 -DCMAKE_BUILD_TYPE=Release -DFREECAD_USE_OCC_VARIANT="Official Version" -DBUILD_QT5:BOOL=ON -DUSE_BOOST_PYTHON:BOOL=OFF -DFREECAD_USE_PYBIND11:BOOL=ON -DBUILD_ENABLE_CXX11:BOOL=ON -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 -DBUILD_PLOT:BOOL=OFF -DBUILD_SHIP:BOOL=OFF -DFREECAD_USE_QT_DIALOG:BOOL=ON -DBoost_NO_BOOST_CMAKE:BOOL=ON -DFREECAD_USE_QWEBKIT:BOOL=ON -DBUILD_FLAT_MESH:BOOL=ON ../freecadL3-source > ~/cmakecapture.txt
```

**Comment by macdroid53** [comment]
I have no idea why the difference for the python3 directory, but, I replaced it and the make seemed to get further with this error:
```
[ 39%] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/Utils_ExceptHandlers.cpp.o
[ 39%] Building C object src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/libmesh.c.o
[ 39%] Linking CXX shared library ../../../lib/libSMESH.so
[ 39%] Built target SMESH
make: *** [Makefile:130: all] Error 2

```
[CMakeError.log](https://github.com/realthunder/FreeCAD/files/7190144/CMakeError.log)
[CMakeCache.txt](https://github.com/realthunder/FreeCAD/files/7190146/CMakeCache.txt)

**Comment by realthunder** [comment]
You have already passed the cmake stage, i.e. successfully generated the `Makefile`. Please capture the whole output of your `make` and posted it here.

**Comment by macdroid53** [comment]
This is fresh output of the entire process.

After clearing the build directory I issued this (note, I specified the /usr/bin/python3, I think this is correct?):
```
cmake     -DOCCT_CMAKE_FALLBACK=1     -DCMAKE_BUILD_TYPE=Release     -DFREECAD_USE_OCC_VARIANT="Official Version"     -DBUILD_QT5:BOOL=ON     -DUSE_BOOST_PYTHON:BOOL=OFF     -DFREECAD_USE_PYBIND11:BOOL=ON     -DBUILD_ENABLE_CXX11:BOOL=ON     -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3     -DBUILD_PLOT:BOOL=OFF     -DBUILD_SHIP:BOOL=OFF     -DFREECAD_USE_QT_DIALOG:BOOL=ON     -DBoost_NO_BOOST_CMAKE:BOOL=ON     -DFREECAD_USE_QWEBKIT:BOOL=ON     -DBUILD_FLAT_MESH:BOOL=ON ../freecadL3-source > ~/cmakecapture.txt
```
[cmakecapture.txt](https://github.com/realthunder/FreeCAD/files/7192042/cmakecapture.txt)

When it was complete, I entered:
```
make -j5 >~/makecapture.txt
```
[makecapture.txt](https://github.com/realthunder/FreeCAD/files/7192044/makecapture.txt)


And other output from the terminal:
[maketerminaloutput.txt](https://github.com/realthunder/FreeCAD/files/7192045/maketerminaloutput.txt)

**Comment by realthunder** [comment]
No. It should be `/usr/local/bin/python3`.

**Comment by macdroid53** [comment]
Using /usr/local/bin/python3:

```
cmake     -DOCCT_CMAKE_FALLBACK=1     -DCMAKE_BUILD_TYPE=Release     -DFREECAD_USE_OCC_VARIANT="Official Version"     -DBUILD_QT5:BOOL=ON     -DUSE_BOOST_PYTHON:BOOL=OFF     -DFREECAD_USE_PYBIND11:BOOL=ON     -DBUILD_ENABLE_CXX11:BOOL=ON     -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3     -DBUILD_PLOT:BOOL=OFF     -DBUILD_SHIP:BOOL=OFF     -DFREECAD_USE_QT_DIALOG:BOOL=ON     -DBoost_NO_BOOST_CMAKE:BOOL=ON     -DFREECAD_USE_QWEBKIT:BOOL=ON     -DBUILD_FLAT_MESH:BOOL=ON ../freecadL3-source > ~/cmakecapture.txt
```

Results in:

```
CMake Error at cMake/FreeCAD_Helpers/SetupPython.cmake:137 (message):
  =================================

  Python not found, install Python!

  =================================

Call Stack (most recent call first):
  CMakeLists.txt:45 (SetupPython)

```
[cmakecapture.txt](https://github.com/realthunder/FreeCAD/files/7192133/cmakecapture.txt)


Maybe because what's in /usr/local/bin is python3.7  ??

**Comment by realthunder** [comment]
Ah, right, it should be `/usr/local/bin/python3.7`. Please check the path to make sure you actually have this file.

**Comment by macdroid53** [comment]
With python3.7 it now completes but reports:

```
ModuleNotFoundError: No module named 'PySide2'
================================
PySide2 Python module not found.
================================
```

Interesting there is also /usr/local/bin/ptyhon3.7m
???

**Comment by realthunder** [comment]
Can you please post the whole cmake output and CMakeCache.log? CMake's output is often misleading. Not all error is actually fatal. `CMakeError.log` is even more unreliable. A better way is to search for message `Configuring incomplete, errors occurred!`.

**Comment by macdroid53** [comment]
[cmakecapture.txt](https://github.com/realthunder/FreeCAD/files/7192196/cmakecapture.txt)


Do you mean CMakeCache.txt? I can't find a CMakeCache.log.
[CMakeCache.txt](https://github.com/realthunder/FreeCAD/files/7192203/CMakeCache.txt)

**Comment by realthunder** [comment]
Like I suspected, cmake completes fine. Just look for the 'Configuration done' message at the end. You can make now. Please capture the full output.

**Comment by macdroid53** [comment]
It does not complete. 

All output and terminal output.

[makecapture.txt](https://github.com/realthunder/FreeCAD/files/7192254/makecapture.txt)
[maketerminaloutput.txt](https://github.com/realthunder/FreeCAD/files/7192255/maketerminaloutput.txt)

**Comment by realthunder** [comment]
It's strange that cmake insists on using the static Python library. There must be something special with the Python installation on your system. The following command manually specifies all python settings. Please re-run cmake, and then make and capture all outputs

```
cmake \
    -DOCCT_CMAKE_FALLBACK=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DFREECAD_USE_OCC_VARIANT="Official Version" \
    -DBUILD_QT5:BOOL=ON \
    -DUSE_BOOST_PYTHON:BOOL=OFF \
    -DFREECAD_USE_PYBIND11:BOOL=ON \
    -DBUILD_ENABLE_CXX11:BOOL=ON \
    -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.7 \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m \
    -DPYTHON_LIBRARY=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.so \
    -DBUILD_PLOT:BOOL=OFF \
    -DBUILD_SHIP:BOOL=OFF \
    -DFREECAD_USE_QT_DIALOG:BOOL=ON \
    -DBoost_NO_BOOST_CMAKE:BOOL=ON \
    -DFREECAD_USE_QWEBKIT:BOOL=ON \
    -DBUILD_FLAT_MESH:BOOL=ON \
    ..
```

**Comment by macdroid53** [comment]
That appears to have build successfully.

Not sure what messed with the python configuration on this Debian machine...

**Comment by macdroid53** [comment]
With the latest git pull I attempted to build with the following:
`cmake     -DOCCT_CMAKE_FALLBACK=1     -DCMAKE_BUILD_TYPE=Release     -DFREECAD_USE_OCC_VARIANT="Official Version"     -DBUILD_QT5:BOOL=ON     -DUSE_BOOST_PYTHON:BOOL=OFF     -DFREECAD_USE_PYBIND11:BOOL=ON     -DBUILD_ENABLE_CXX11:BOOL=ON     -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.7     -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m     -DPYTHON_LIBRARY=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.so     -DBUILD_PLOT:BOOL=OFF     -DBUILD_SHIP:BOOL=OFF     -DFREECAD_USE_QT_DIALOG:BOOL=ON     -DBoost_NO_BOOST_CMAKE:BOOL=ON     -DFREECAD_USE_QWEBKIT:BOOL=ON     -DBUILD_FLAT_MESH:BOOL=ON ~/freecadL3-source
`

and received the following error:
`...
[ 42%] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/Utils_ExceptHandlers.cpp.o
[ 42%] Linking CXX shared library ../../../lib/libSMESH.so
[ 42%] Built target SMESH
make: *** [Makefile:130: all] Error 2
`
Not sure what changed...

**Comment by realthunder** [comment]
The default branch has been merged with upstream 0.20, which now requires C++17 to compile. Please change `-DBUILD_ENABLE_CXX11` to `-DBUILD_ENABLE_CXX_STD:STRING=C++17`.

**Comment by macdroid53** [comment]
Sorry, didn't work:
`/home/mac/freecadL3-source/src/Base/UnitsApi.cpp:150:31: note: ‘std::make_unique’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
/home/mac/freecadL3-source/src/Base/UnitsApi.cpp:150:62: error: expected primary-expression before ‘>’ token
         UserPrefSystem = std::make_unique<UnitsSchemaInternal>();
                                                              ^
/home/mac/freecadL3-source/src/Base/UnitsApi.cpp:150:64: error: expected primary-expression before ‘)’ token
         UserPrefSystem = std::make_unique<UnitsSchemaInternal>();
                                                                ^
[ 41%] Building CXX object src/Base/CMakeFiles/FreeCADBase.dir/UnitPyImp.cpp.o
make[2]: *** [src/Base/CMakeFiles/FreeCADBase.dir/build.make:917: src/Base/CMakeFiles/FreeCADBase.dir/UnitsApi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 43%] Built target StdMeshers
make[1]: *** [CMakeFiles/Makefile2:792: src/Base/CMakeFiles/FreeCADBase.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by macdroid53** [comment]
That fixed it.

Thanks!
