### ISSUE TITLE
Crash when trying to copy body

### ISSUE THREAD

**Issue by MatthiasKohler** [realthunder/FreeCAD#18]
When trying to copy a body, FreeCAD crashes. 

Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fe4d1f90f20]
#1  /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5(+0x2f061a) [0x7fe4d2c2761a]
#2  0x7fe4d2c29dfd in QHeaderView::resizeSection(int, int) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5+0xb3
#3  0x7fe4d4490876 in Gui::DlgObjectSelection::DlgObjectSelection(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, QWidget*, QFlags<Qt::WindowType>) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libFreeCADGui.so+0x176
#4  0x7fe4d4757b01 in Gui::MainWindow::createMimeDataFromSelection() const from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libFreeCADGui.so+0x171
#5  0x7fe4d43d277f in StdCmdCopy::activated(int) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libFreeCADGui.so+0x2f
#6  0x7fe4d43ce3e3 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libFreeCADGui.so+0x323
#7  0x7fe4d26e0e34 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Core.so.5+0x780
#8  0x7fe4d2a9e01a in QAction::triggered(bool) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5+0x32
#9  0x7fe4d2a9f8d9 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5+0xcb
#10  0x7fe4d2a9ffdd in QAction::event(QEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5+0xaf
#11  0x7fe4d2aa2ca0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5+0xde
#12  0x7fe4d2aa8b19 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Widgets.so.5+0x1a81
#13  0x7fe4d43942a9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libFreeCADGui.so+0x89
#14  0x7fe4d26cc21a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Core.so.5+0x88
#15  0x7fe4d1046214 in QShortcutMap::dispatchEvent(QKeyEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libQt5Gui.so.5+0xd4
#16  0x7fe4d104627d in QShortcutMap::tryShortcut(QKeyEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libQt5Gui.so.5+0x55
#17  0x7fe4d101d649 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libQt5Gui.so.5+0xab
#18  0x7fe4d102c13e in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libQt5Gui.so.5+0xac
#19  0x7fe4d102ef7b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libQt5Gui.so.5+0x187
#20  0x7fe4d101b4ae in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libQt5Gui.so.5+0x58
#21  /tmp/.mount_FreeCAtJkO14/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x7ed90) [0x7fe4cc271d90]
#22  /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x2e8) [0x7fe4ce72f9d8]
#23  /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libglib-2.0.so.0(+0x51c21) [0x7fe4ce72fc21]
#24  /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7fe4ce72fcae]
#25  0x7fe4d26f886f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Core.so.5+0x63
#26  0x7fe4d26c8e47 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Core.so.5+0x187
#27  0x7fe4d26cca3b in QCoreApplication::exec() from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libQt5Core.so.5+0x105
#28  0x7fe4d430fd04 in Gui::Application::runApplication() from /tmp/.mount_FreeCAtJkO14/usr/bin/../lib/libFreeCADGui.so+0x1534
#29  ./FreeCAD(main+0x725) [0x558b1791b7a5]
#30  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fe4d1f73b97]
#31  ./FreeCAD(+0x44d5) [0x558b1791c4d5]

OS: Ubuntu 18.04.3 LTS (i3/i3)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16830 +1496 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 1b29767b545440b7ab93f1a5f2b742d622f1b547
Python version: 3.7.3
Qt version: 5.9.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

**Comment by realthunder** [comment]
Please pull branch LinkStage3. This bug is fixed.

**Comment by luzpaz** [comment]
@realthunder can this ticket be closed?

**Comment by luzpaz** [comment]
@realthunder close ticket
