### ISSUE TITLE
Save/load Job in a folder

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD#19]
Hello,
I can't load file with simple job saved in a folder:
Branch: LinkStage3 commit 3aacedd809e8ecf28f910063fbdbc9d0891e8ec4

![job-folder](https://user-images.githubusercontent.com/6075465/64932599-8c705c00-d883-11e9-9e03-9dd0bbdabfb3.gif)

**Comment by realthunder** [comment]
Should be fixed now. Thanks for reporting.

**Comment by yrabbit** [comment]
Thanks for such a quick fix. Everything is working.
