### ISSUE TITLE
Pad / pocket type "up to face" is broken in LinkDaily

### ISSUE THREAD

**Issue by xplwowi** [realthunder/FreeCAD#194]
Selecting targets: face, binder, datum plane, ... creates broken geometry.

**Comment by realthunder** [comment]
Please attach a sample file showing the problem, and also paste your FreeCAD about information here. Thanks

**Comment by xplwowi** [comment]
Hi. It was broken for about two weeks. Even with the simpliest models. AFAIR broken versions automatically created binder within active body when the plane (even X-Y) was used as a reference. I build your branch from sources quite regularly. Just synced repo and now everything works again.
Thanks for all your great work!

OS: Ubuntu 21.04 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28572 (Git)
Build type: Unknown
Branch: LinkDaily
Hash: fcb79d874627103151e95209819a5166d4f37254
Python version: 3.9.5
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
