### ISSUE TITLE
Boolean Union Object wrongly visualized as separate objects

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#195]
The following document worked smoothly until today after I synced my local sources with the linkdaily repo.

[CMP_KaCh3_SFILT_6_4.zip](https://github.com/realthunder/FreeCAD/files/7340542/CMP_KaCh3_SFILT_6_4.zip)

With the previous build (synced about one week ago) the same document was recomputed smoothly several times after applying small changes to the values of the variables spreadsheet (which controls a set of geometrical dimensions). 

Now it fails after any small change of those values.

The following error message (which you may reproduce using the annexed file) is repeated several times:

> <Exception> Null shape
> <Part> SubShapeBinder.cpp(406): CMP_KaCh3_SFILT_6_4#Binder001 failed to obtain shape from CMP_KaCh3_SFILT_6_4#Body006.Boolean001.Reference002.?Face75

**Comment by realthunder** [comment]
Please post your FreeCAD about information here. Which variable did you change? I changed many without error. I even did a full recompute of the document without error.

**Comment by wsteffe** [comment]
Hello RT, thanks for replay. It happened with any variable change. In example you may change the first one from 8.8117 to 8.8118.  The change of a variable is just a mean to force a recompute of all document.  
I have still to check but now I am thinking that, probably, the problem originated from the last commit:  Part: fix FaceUniter.
I had observed that in the previous design the faces with same geometrical surfaces were not united after Boolean001.
Now probably they are and the number of faces in Boolean001 has been reduced so that the face 75 has been tagged with a different number. 
I still have to check (and I will let you know) but if it is so it is not a regression, eventually just a case that your TopoNaming algorithm was not able to handle.

FreeCAD information is here below:

OS: Ubuntu 20.04.3 LTS (GNOME-Flashback:GNOME/gnome-flashback-metacity)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28572 (Git)
Build type: Unknown
Branch: LinkDaily
Hash: fcb79d874627103151e95209819a5166d4f37254
Python version: 3.8.10
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by wsteffe** [comment]
I have just checked and now I think that my hypothesis was not correct.
Now the document has been fixed with last build through deletion and recreation of bad pointing subshapebinders. 
But, as you may seen from annexed screenshot, the faces with same geometrical surfaces are still not united in Boolean001.
![Screenshot from 2021-10-14 09-36-05](https://user-images.githubusercontent.com/12879321/137273536-23d59372-4e79-49d3-af0e-77034468bf28.png)

The situation is a little bit confusing to me because the selection of a face in the 3D window produces, in the model tree, the selection of just one member (CAVITY_TOP) of Boolean001 and not of the result Boolean001.

Another strange thing is that, when the two members (Reference001 and Reference002) are hidden, Boolean001 object is also not visible.  It is like as the Boolean001 object were a container of two separate objects instead of a true union.
But in the exported step file DIEL_CAVITY (the body which contains Boolean001) appears as a single solid. A very strange behaviour.

**Comment by wsteffe** [comment]
Hello RT, I have changed the issue title because:
1) Even if I do not have understood where the initial issue come from there was an easy solution for that: To recreate lost subshape binders.
2) That problem was not reproducible in your build.
3) The wrong visualization of the boolean object (individual components instead of union result) is a major issue in my opinion.

I think that it is a visualization problem because in the step file there is single solid (and not the two parts involved in the boolean operation). The wrong representation occurs in the Model Tree and also in 3D window. In fact the appearance (colors transparency) of the two parts must be set in the two components (Reference001 and Reference002) while the setting of appearance for Boolean001 doesn't have any effect.
