### ISSUE TITLE
PartDesign pocket Up to face fails with non zero Offset to face

### ISSUE THREAD

**Issue by rmTizi** [realthunder/FreeCAD#197]
Basically the title, just making any kind of pocket with type Up to face and trying to set an offset, either positive or negative, causes the feature to fail.

Works in 0.19.2 main branch.

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.922.24301 +4188 (Git)
Build type: Release
Branch: LinkDaily
Hash: 3de879c7a2ba7111cc769d98636eb6d43189459d
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)
````

Attached is a minimum file reproducing the bug.
[negative offset to face failed.zip](https://github.com/realthunder/FreeCAD/files/7341705/negative.offset.to.face.failed.zip)

**Comment by xplwowi** [comment]
I confirm. Problem I have reported under #194 with zero-offset has been solved but the new one appeared. The symptoms are the same as in that case.

**Comment by realthunder** [comment]
@rmTizi Should be fixed. Please try.

**Comment by xplwowi** [comment]
It works for me again. Thanks!

**Comment by rmTizi** [comment]
@realthunder Confirmed, thanks for the fast fix.
