### ISSUE TITLE
Update CMakeLists.txt from upstream

### ISSUE THREAD

**Issue by christian-nils** [realthunder/FreeCAD#200]
Hi-

I was trying to build the LinkDaily branch from scratch on Fedora 34. I had the same issue that I had some months ago with the official FreeCAD source code (https://forum.freecadweb.org/viewtopic.php?f=4&t=57247&start=10). They changed the order of the setups in order to set up the Boost library "correctly" (https://github.com/FreeCAD/FreeCAD/commit/b64c4da51b6eea86eb7dcf710c72e213b1c06f25#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a). But since this change was not pulled to this fork, the compilation from source fails.

So I wonder if someone could update CMakeLists.txt to make this repository succeed with Fedora machines?

Thanks,

Greetings,

CN

**Comment by realthunder** [comment]
I've synced with upstream recently. Please try again.

**Comment by luzpaz** [comment]
@realthunder ticket can be closed

**Comment by christian-nils** [comment]
Yes, sorry for not answering. It worked with the new sync. Thanks!
