### ISSUE TITLE
question (not an issue) - order of things in tree view

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD#203]
Is it possible to re-arrange the order of items listed in the tree view?
Functionally it doesn't make any difference to FreeCAD, but to me as a user keeping things tidy and in (my preferred) order makes things easy to handle.
Unfortunately depending on the order I create things, they end up listed a bit randomly (from my human/user point of view)...

I know that in Assembly 3 one can arrow things up and down easily - is this (or something similar) possible in link branch tree view outside of Assembly 3? 
or... is it still down to main branch and it's limitations?
(see: https://github.com/FreeCAD/FreeCAD/pull/4626)

**Comment by wohltat** [comment]
I really miss sorting elements in tree view. Optimally this should be as simple as dragging it to another position with a line indicating where it will be placed.

**Comment by bambukouk** [comment]
Thank you @realthunder 
Hopefully it will not suffer from the problems described on FreeCAD forum :+1:

**Comment by wohltat** [comment]
awesome, looking forward to see this in action
