### ISSUE TITLE
LinkStage3/Stable branch does not exist

### ISSUE THREAD

**Issue by ppd** [realthunder/FreeCAD#204]
https://github.com/realthunder/FreeCAD_assembly3/releases refers to the `LinkStage3` and `LinkDaily` branches.
LinkDaily exists, but LinkStage3 does not. Is that a temporary thing, or am I misreading the change log?

I'm playing with the idea of setting up a snap package for your fork (based on https://github.com/ppd/freecad-ppd). For this, I'd do `stable` builds from your stable branch and `edge` builds from `LinkDaily`, hence the question.

**Comment by ceremcem** [comment]
Here it is: https://github.com/realthunder/FreeCAD/tree/LinkStage3

**Comment by ppd** [comment]
Thank you. Must've been the dreaded morning branch-blindness.
