### ISSUE TITLE
Broken job default action with folder save/load

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD#21]
Hello,
Loading file with simple job saved in a folder leads to incorrect click action on the Job. 
Non-folder save/load is ok.
![job-folder-1](https://user-images.githubusercontent.com/6075465/65232980-71b51600-db15-11e9-9355-a54ecccf2fb6.gif)

Branch: LinkStage3 commit d9f36118c9858ee78ff2e854c41c42749fd55e8b

**Comment by realthunder** [comment]
Should be fixed. You have to save a fresh copy to fix the problem.

**Comment by yrabbit** [comment]
Thank you!
