### ISSUE TITLE
[Minor] Missing icon `TreeDragReorder.svg`

### ISSUE THREAD

**Issue by scottmudge** [realthunder/FreeCAD#216]
It will probably be added soon, but just making a note that `TreeDragReorder.svg` is missing but required by the latest commits to `LinkDaily`:

```
RCC: Error in 'C:/Development/3D/FreeCAD/src/Gui/Icons/resource.qrc': Cannot find file 'TreeDragReorder.svg'
```

**Comment by wsteffe** [comment]
Yes, I have the some problem: 
```
Building ViewProviderPy.h/.cpp out of ViewProviderPy.xml
make[2]: *** No rule to make target '../src/Gui/Icons/TreeDragReorder.svg', needed by 'src/Gui/qrc_resource.cpp'.  Stop.

```

**Comment by scottmudge** [comment]
For the time being it's possible to copy and paste an existing icon to fill the role of the missing icon.

**Comment by realthunder** [comment]
Fixed. Thanks for the heads up.
