### ISSUE TITLE
Copy/paste error?

### ISSUE THREAD

**Issue by KuzemkoA** [realthunder/FreeCAD#232]
https://github.com/realthunder/FreeCAD/blob/b527359e936433d504b788ae54af12a60258781f/src/App/Expression.cpp#L5211

**Comment by wohltat** [comment]
most likely `c2.isValid()` is meant

**Comment by KuzemkoA** [comment]
https://github.com/realthunder/FreeCAD/blob/b527359e936433d504b788ae54af12a60258781f/src/App/PropertyStandard.cpp#L1151-L1157

 else if (value.type() == typeid(long)) twice

**Comment by realthunder** [comment]
Fixed. Thanks for the heads up.
