### ISSUE TITLE
make install recompiles many souce files

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#245]
Usually I am building FC inside a "build" subdir with following commands:

```
make
sudo make install
```

Installation is done with root privileges because it goes into /usr/local

Before last sync "sudo make install" was very fast. 
But now it takes a long time because it recompiles many files.

**Comment by realthunder** [comment]
That's not really a bug. It just happened that a recent fix changes a core file that's included in many other files, causing the need to rebuild.

There are various ways to reduce rebuild time on changes like that, but it require considerable refactor of the core libraries, and is not worth it at the moment, IMO.
