### ISSUE TITLE
LinkStage3 branch lacks "Export selected geometries as ..." Sketcher actions

### ISSUE THREAD

**Issue by bgamari** [realthunder/FreeCAD#25]
The [Assembly3 0.10.2 AppImage](https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.10.2) has a very handy pair of actions in Sketcher: "Export selected geometries as separate child objects" and "Export selected geometries as single child objects".

However, I am finding that my own build of the `LinkStage3` branch (specifically commit f97f6b41b172b5ac65b95b62b5bc43087f44e539) and `asm3` branch (specifically https://github.com/realthunder/FreeCAD_assembly3/commit/b7da4ecc416f759dd44c6ffef22225dd76d035bd) seems to lack these actions. Were these introduced in another branch? What exactly are the AppImages built from?

**Comment by realthunder** [comment]
Where do you get the commit f97f6b41b172b5ac65b95b62b5bc43087f44e539. I could find it.

**Comment by bgamari** [comment]
Whoops; my apologies. That was the `solvespace` commit. I am using FreeCAD commit 2ca84062e736ccc563fad584e675df4804c57031.

**Comment by realthunder** [comment]
The buttons are still there. You can't find them on toolbar?

![Screenshot from 2019-11-12 06-43-07](https://user-images.githubusercontent.com/1207888/68627208-2c5f0480-0518-11ea-865d-c3a063b6ee6e.png)

**Comment by bgamari** [comment]
Indeed they are not in the toolbar with 2ca8406. Which commit introduced this feature?

**Comment by realthunder** [comment]
Can you please post a screenshot of the toolbar when editing a sketch? The buttons were added by [this](https://github.com/realthunder/FreeCAD/blob/2ca84062e736ccc563fad584e675df4804c57031/src/Mod/Sketcher/Gui/Workbench.cpp#L208) line.

**Comment by bgamari** [comment]
Done.

![FreeCAD](https://user-images.githubusercontent.com/1010174/68635259-f6913000-04c5-11ea-9b7d-52b785cefd56.png)

**Comment by realthunder** [comment]
That's strange. Are you sure you are running my branch? Can you paste what's in the 'About' window?

Also when you scroll down the task panel here, did you see the Element listbox headers?

![Screenshot from 2019-11-12 10-04-22](https://user-images.githubusercontent.com/1207888/68635608-152e1000-0534-11ea-8492-ac93a57c0922.png)

**Comment by bgamari** [comment]
Oh dear; indeed I was building a different tree than I thought. My apologies for the hassle.
