### ISSUE TITLE
Snap description references wrong command

### ISSUE THREAD

**Issue by ppd** [realthunder/FreeCAD#259]
From snap info freecad-realthunder:

>   **Apps/Commands**
>   
>   There are multiple apps/commands included in the snap:
>   
>   * **freecad-realthunder.freecad**: Run FreeCAD

In your snap however, the main command was renamed to freecad-realthunder, which results in a _non-namespaced_ freecad-realthunder  command without the `.freecad` suffix.
In my snap, the app name is not identical to the snap name, which results in the namespaced freecad-ppd.freecad command.

**Comment by realthunder** [comment]
Thanks for the heads up! Just corrected it now.
