### ISSUE TITLE
Fillet of Part workbench crash in debug mode (visual studio 2015)

### ISSUE THREAD

**Issue by print21** [realthunder/FreeCAD#26]
I build the latest freecad code of the LinkStage3 branch with VS2015 and libpack of FreeCADLibs_12.1.3_x64_VC15.

The crash happens when fillet operation in Part workbench and in debug mode.
![微信截图_20191129112233](https://user-images.githubusercontent.com/29243556/69841548-9d354900-129a-11ea-8f7b-2c4a900bf245.png)

Same operation performed in release mode and report view shows error of "PyEval_EvalFrameEx returned a result with an error set".

I debug the code and found that: when set the value of fillet “Edges”, the crash happened.
In "PropertyFilletEdges::getPyValue()" function, the “PyObject *item” is a list not a tuple, so python exception throw. the "PropertyListsT::setPyObject()" function dose not handle the python exception.

So i did some tests.

First i changed the code in "PropertyFilletEdges::getPyValue()". i checked the type of “PyObject *item”, when it was not a tuple, a Base::ValueError exception trowed. Then the crash aforementioned did not happen.
![微信截图_20191129105257](https://user-images.githubusercontent.com/29243556/69841577-c524ac80-129a-11ea-8a1d-b5bdca0050cf.png)

Second, i restored the code in "PropertyFilletEdges::getPyValue()". i modified the code of "PropertyListsT::setPyObject()" in catch scope. When “Py::Exception" caught, i cleared the python exception.  Then the crash aforementioned did not happen too.
![微信截图_20191129104940](https://user-images.githubusercontent.com/29243556/69841586-cc4bba80-129a-11ea-8204-8e25d1881171.png)

So i guess that the assert was triggered caused by “Py::Exception" and crash happened.
and i suggest the first modification to fix this problem because the include file of “Py::Exception" will be included in “Property.h” with the second change.
![微信截图_20191129105006](https://user-images.githubusercontent.com/29243556/69841695-39f7e680-129b-11ea-8f29-bea53602a585.png)

**Comment by realthunder** [comment]
PropertyListT::getPyValue() is not supposed to throw any Py::Exception. It is supposed to catch and translate the exception to various Base::Exception. I have fixed this now. Thanks for digging in!
