### ISSUE TITLE
Segfault in FreeCAD snap on Ubuntu 20.04

### ISSUE THREAD

**Issue by troetter** [realthunder/FreeCAD#261]
I've just installed the freecad-realthunder snap, version string "2022-01-27-g62d7d3f3", and almost immediately I run into a segfault. I have attached the minimal file where the crash occurs, along with a stack trace and the link.user.cfg file that I've seen requested in other issues. It doesn't happen in the exact same place in the UI every time, but it is easily reproducible on my end. Most frequently when performing these steps:

1. Open sketch
2. Place horizontal dimensional constraint on top line
3. Set value to reference "<<Dimensions>>.profile_width", press Ok
4. Crash, sometimes instantly, sometimes after moving the mouse around for a bit

Please let me know if anything else is needed.

[segfault.zip](https://github.com/realthunder/FreeCAD/files/7951756/segfault.zip)

**Comment by realthunder** [comment]
Fixed by ec0fcee41ff6847a7649fef18b0dc00202a52a27. Will make a new build soon.
