### ISSUE TITLE
Bug: Visibility controls no longer functioning

### ISSUE THREAD

**Issue by jj-uk** [realthunder/FreeCAD#264]
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2022.111.28429 (Git)
Build type: Release
Branch: LinkStage3
Hash: ec814c42d02f15171f9dbb7f650400c9943abfe0
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United Kingdom (en_GB)

None of the visibility controls are working.

I can open and save the file in 0.19 (official), then open it in LinkStage3, but after a few minutes of using the application, the visibility tools stop working again.

What can I do to repair the file? 

[cp-linkBranch.20220129-170948 - Copy.zip](https://github.com/realthunder/FreeCAD/files/7964937/cp-linkBranch.20220129-170948.-.Copy.zip)

**Comment by DerTFL** [comment]
Hi! Can you try method described in this issue comment?: https://github.com/realthunder/FreeCAD_assembly3/issues/1087#issuecomment-1022243000

**Comment by jj-uk** [comment]
Yes, pressing `CTRL + SHIFT + SPACE` with no objects selected has works for me, thanks,
