### ISSUE TITLE
Unable to include geometry from one sketch to another

### ISSUE THREAD

**Issue by troetter** [realthunder/FreeCAD#265]
I'm trying to learn FreeCAD coming from other software, and I'm trying to figure out a workflow that works. I have convinced myself this is a bug, but I could be mistaken, maybe I'm supposed to do things in a different way?

I'm using the freecad-realthunder snap on Ubuntu 20.04, version string "2022-01-28-gec0fcee4".

Steps to reproduce:
1. New file
2. Create part
3. Create body
4. Create sketch
5. Draw rectangle in sketch, close
6. Create sketch on same plane as the first
7. Include line from first sketch using 'External geometry'
8. Error

The Report view says:
`10:01:02  1.605954 <asm3.main> init_gui.py(14): no solver backend found
10:13:15  <Sketch> SketchObject.cpp(7760): Unknown type of geometry in Unnamed#Sketch001: Sketch.
10:13:15  App.getDocument('Unnamed').getObject('Sketch001').addExternal(Part.importExternalObject((FreeCAD.getDocument('Unnamed').getObject('Part'), 'Body.Sketch.'), (FreeCAD.getDocument('Unnamed').getObject('Part'), 'Body.Sketch001.')), False)
10:13:15  Failed to add external geometry: Not able to add external shape element`

I haven't found any difference if I save the file and reopen in, rename the part, body or sketches or something like that, but I'm certain I haven't tried every combination. I have tried the same thing in upstream v19.3, and there it works, so I assume it should here as well.

**Comment by Rabbit-sk** [comment]
Just for information, the error did not appear in the Windows build. 

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git)
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: Slovak/Slovakia (sk_SK)
