### ISSUE TITLE
Compile errors due to include order with latest changes, on Windows

### ISSUE THREAD

**Issue by scottmudge** [realthunder/FreeCAD#276]
This affects the most recent commits (last few days).

The include/import order is incorrect in `DocumentObject.cpp`, leading to compiler errors on Windows.

Because `PreCompiled.h` imports `FCConfig.h`, which contains the DLL import/export macros, if this is included *after* other headers which use these import/export macros, compiler errors occur.

This is limited to Windows.

The fix is to re-order the imports such that `PreCompiled.h` or `FCConfig.h` is included before any other headers:

![image](https://user-images.githubusercontent.com/19617165/154035374-e1717bde-9b90-434c-ab55-9e6e9de9bbc3.png)

**Comment by realthunder** [comment]
Wow, what a silly mistake I was making. I don't understand how it got there. I don't remember doing that. Must have triggered some auto fix feature in the intellisense somehow. Thanks for the heads up!

**Comment by scottmudge** [comment]
It happens. If I use the feature which automatically adds missing imports/includes with Visual Assist, it seems to put them randomly at the top of the file, sometimes before other includes. Probably just an automatic bug.

**Comment by scottmudge** [comment]
Thanks for the quick fix! 👍
