### ISSUE TITLE
LinkDev: can't compile windows

### ISSUE THREAD

**Issue by rgbertoni** [realthunder/FreeCAD#28]
Hi realthunder, thank you for your amazing work. Your implementations allowed me to start my project.
I´m trying to compile LinkDev on windows but I can't success. I'm getting the following error:
=>>> freecad\src\base\Base64.h(73): error C2059: syntax error: '__declspec(dllexport)'
I'm using windows 10 and FreeCADLibs_12.1.4_x64_VC15. Same error with FreeCADLibs_12.1.2_x64_VC15.

**Comment by realthunder** [comment]
Made some changes. Please try.

**Comment by rgbertoni** [comment]
Hi the Base64.h was solved but now I got another ones.


Error	C2512	'std::basic_istream<char,std::char_traits<char>>': no appropriate default constructor available	FreeCADBase	D:\AtConcept\rgbertoni\FreeCAD\src\Base\Reader.cpp	641	

[error-compile.log](https://github.com/realthunder/FreeCAD/files/4287655/error-compile.log)

**Comment by realthunder** [comment]
Should be working now. I have tried it on my side.

**Comment by realthunder** [comment]
Oops, no. Still has problem. Hang on there.

**Comment by realthunder** [comment]
Okay, now it should be fine, I hope...

**Comment by rgbertoni** [comment]
It worked !!! Thank you.
