### ISSUE TITLE
Treeview reordering not working for Linked Objects

### ISSUE THREAD

**Issue by barry30** [realthunder/FreeCAD#281]
Hi,
It seems if you have several Linked Objects, you can't reorder one of them with respect to other Linked Objects.  They can be moved above/below Bodies, but not other Linked Objects.

OS: Devuan GNU/Linux 4 (chimaera) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Can you please provide a file showing the problem?

**Comment by barry30** [comment]
In Part2, I can't move Link(Body4) to be above Link(Body3) but in Part1, I can move Body2 to be above Body1.

I believe this behavior is the same, where using a Part or not.


(File renamed to .zip for upload)
[tree_reorder_test.zip](https://github.com/realthunder/FreeCAD/files/8116415/tree_reorder_test.zip)

**Comment by barry30** [comment]
Did you want something else other than a test file, or maybe you haven't had time to look at it?

**Comment by realthunder** [comment]
Yeah, a bit busy. I'll definitely check this out.

**Comment by realthunder** [comment]
I can't seem to reproduce the problem. Can you please make a screen cast? Also, please send me you user config file, `Tools -> Edit parameters -> Export`.

**Comment by barry30** [comment]
Please find attached config file and video.

[freecad_link_daily_params.txt](https://github.com/realthunder/FreeCAD/files/8193126/freecad_link_daily_params.txt)



https://user-images.githubusercontent.com/100158063/156929172-985b06eb-4cbb-41fd-857b-a4bc24c5cb52.mp4

**Comment by realthunder** [comment]
Still can't reproduce the problem. Are you for some reason holding the `Alt` key while dragging?

**Comment by barry30** [comment]
I was holding Ctrl+Alt which is what I thought the pop-up text was saying to do.  I see now that was completely wrong. Unfortunately, since it worked on Bodies it never occurred to me how I was doing it was not correct.

I'm very sorry for wasting your time!
