### ISSUE TITLE
Basefeature doesn't support multiple solids from other body/link

### ISSUE THREAD

**Issue by adrianinsaval** [realthunder/FreeCAD#29]
Attached example (change .zip tp .FCStd), while trying out a link as a basefeature I noticed only the first solid was used, the same happens when using the body directly.
[basefeature-example.zip](https://github.com/realthunder/FreeCAD/files/4531216/basefeature-example.zip)

**Comment by realthunder** [comment]
Yes, this problem is caused by SubShapeBinder using the old TopoShape::fuse() instead of the new makEFuse(). As a temporary work around, set the binder.Fuse to False to get multiple solids.
