### ISSUE TITLE
[Request] TechDraw

### ISSUE THREAD

**Issue by not-a-number-dot-org** [realthunder/FreeCAD#292]
Hello

Can you please release a stable version with the TechDraw extensions (add circle centerlines, etc...)

Also please see bug in TechDraw https://forum.freecadweb.org/viewtopic.php?f=35&t=67068 (it is my understanding that expressions in property editor exists because of this fork... may be wrong)

Thanks in advance

**Comment by luzpaz** [comment]
Closing in favor of realthunder/FreeCAD#323
