### ISSUE TITLE
File icons are disabled

### ISSUE THREAD

**Issue by berniev** [realthunder/FreeCAD#335]
OS: macOS 10.16
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2022.407.28576 (Git)
Build type: Release
Branch: LinkStage3
Hash: 599f7663af69d3dbd77063e834b12f26da513b2d
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: C/Default (C)

File Open and File New icons disabled. Equiv menu ok.

New here. Do you want this sort of reporting?

**Comment by realthunder** [comment]
Yes sure. Thanks for reporting!
