### ISSUE TITLE
Installing in Manjaro problems..

### ISSUE THREAD

**Issue by Prutzz** [realthunder/FreeCAD#339]
Been busy couple of days to get some software(influxdb and Grafana) running under Manjaro but with not much luck, Realthunder version is also one of those software which I can't get it installed... I'm kinda new to Linux and very determined to get to learn linux well. But now I'm slowly getting on a point I want to toss the towel in the ring.. 

I tried to install it with the package manager and the AUR repos. But when building I'm getting a fault.

Then I've installed FreeCAD through the official Manjaro repos and downloaded the "FreeCAD_assembly3-master.zip". Wanted to extract it to the "/home/<your_user_name>/.FreeCAD/Mod" folder... But there is no /.FreeCAD/ folder? Seems I'm missing something out?

Also downloaded this file but have no clue what to do with this. "FreeCAD-asm3-Stable-Conda-Py3-Qt5-20210916-glibc2.12-x86_64.AppImage".

**Comment by realthunder** [comment]
For AppImage, just make it executable and run it. Not sure about your OS, but you can also do it in terminal with the following command

```
chmod +x FreeCAD-asm3-Stable-Conda-Py3-Qt5-20210916-glibc2.12-x86_64.AppImage
./FreeCAD-asm3-Stable-Conda-Py3-Qt5-20210916-glibc2.12-x86_64.AppImage
```

**Comment by LouiseTGUK** [comment]
Appimage UI is all to cock on Manjaro and other os's it would seem, the fonts are near on microscopic.. Changing default font size works, but other ui elements like checkboxes are so small they are nearly unusable

I have worked around it by a fix adding 

`exec=/usr/bin/env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1.7`

to the front of the executable but home workbench is mahoosive..

Something to do with QT and the appimage creation but its all beyond my paygrade!

https://github.com/appimage/appimagekit/issues/125

**Comment by ghost** [comment]
> I have worked around it by a fix adding
> 
> `exec=/usr/bin/env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1.7`

There is special variable to scale only fonts:

`exec=/usr/bin/env QT_FONT_DPI=140 ./FreeCAD*.AppImage`

![Screenshot_2023-02-01_21-37-31](https://user-images.githubusercontent.com/13188580/216193962-2c1754a1-2fa8-4edd-a06d-69273f505440.png)
