### ISSUE TITLE
GUI - Axial is reset

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#34]
when editing the PartDisign position... any (almost) changes (offset X, U, rotation around the axes - i.e. any, but we do NOT change the Axial value, where the default is 0mm) when you click OK or Apply, an error message is displayed - the existing Axial value is completely erased and you have to manually go into this field, enter 0mm and click Apply again.

**Comment by tiket18** [comment]
The reason, I think, is that when you open the position editing window, all fields will have default values with the dimension (mm), and Axial will have only values, without mm.

**Comment by realthunder** [comment]
Can you please post a screenshot, or better, capture a screencast showing the problem?

**Comment by tiket18** [comment]
![dsvfn](https://user-images.githubusercontent.com/18741088/83276362-27725180-a1d9-11ea-9b36-ecaa95e2913d.png)

**Comment by realthunder** [comment]
Should be fixed. I'll make a release later today. Thanks for reporting.
