### ISSUE TITLE
Measurement label invisible (w/ experimental renderer)

### ISSUE THREAD

**Issue by OxygenLiu** [realthunder/FreeCAD#345]
![image](https://user-images.githubusercontent.com/4140247/163380079-2eb001dc-2311-46ef-9392-a1a7b5703052.png)

```
OS: Pop!_OS 20.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 2022.407.26244 +4693 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

Screenshot at https://ibb.co/F4wg3dq

_Mod Edit: Added screenshot to the ticket directly for posterity_

**Comment by bambukouk** [comment]
are you using experimental renderer?

**Comment by OxygenLiu** [comment]
yep, experimental render. Switching to Auto render fixes the issue.

**Comment by luzpaz** [comment]
@realthunder is there a way to have the About info display what renderer they're using?

**Comment by scottmudge** [comment]
I noticed this as well.

Edit: In the latest tip of LinkDaily

**Comment by bambukouk** [comment]
![Screenshot from 2022-04-14 16 26 40](https://user-images.githubusercontent.com/50301871/163423071-ee42bafe-f379-4346-8d54-3eac55ec657b.png)

**Comment by scottmudge** [comment]
Well there we go, that answers that.
