### ISSUE TITLE
Building LinkDaily branch returns an error consistently due to "Overlaywidget.cpp"

### ISSUE THREAD

**Issue by projectcad** [realthunder/FreeCAD#353]
I tried many times...but There has been an error due to "overlaywidgets.cpp" consistently..(even only with "make" without using any j2, j3,....)
Thanks in advance
![FreeCAD_Linkdaily_Error](https://user-images.githubusercontent.com/68682837/163665601-6448e488-3050-4b54-9fdc-b885ea819218.png)

..

**Comment by realthunder** [comment]
What is Qt version? Looks like you are using a older Qt.

**Comment by projectcad** [comment]
Qt 5.9.5

**Comment by Kuzma30** [comment]
Update it to Qt version 5.15 and try again.

**Comment by realthunder** [comment]
Please test with the above commit. Feel free to re-open the issue if you still have problem.

**Comment by projectcad** [comment]
It's  OK..thanks..
