### ISSUE TITLE
Transparent Context Menu

### ISSUE THREAD

**Issue by rgbertoni** [realthunder/FreeCAD#38]
Hi, since few last releases, the context menu becomes transparent. Is there a way to return it to solid ?
I'm using windows 10.

![TransparentContextMenu](https://user-images.githubusercontent.com/108377/88489367-4176a900-cf6a-11ea-96f9-1b36213f94d9.png)

**Comment by realthunder** [comment]
I have added a 'Default' menu stylesheet for that purpose. It will be in the next release. If you want to have it now, just copy the [stylesheet](https://github.com/realthunder/FreeCAD/blob/LinkStage3/src/Gui/Stylesheets/menu/Default.qss) to `[user directory]/FreeCAD/data/Gui/Stylesheets/menu/`, and then select it in Preference dialog

**Comment by rgbertoni** [comment]
Thank you.
