### ISSUE TITLE
code pasted to python console is not interpreted correctly 

### ISSUE THREAD

**Issue by wohltat** [realthunder/FreeCAD#388]
I assume it should be possible to copy the code that is automatically generated and logged to the python console and paste it in and it should do the same.

This is not what happens as it throws errors. I tried with the code generated when opening a sketch and get following error
``` python
... if ActiveSketch.ViewObject.HideDependent:
  File "<input>", line 3
    if ActiveSketch.ViewObject.HideDependent:
    ^
SyntaxError: invalid syntax
```

I narrowed it down to following misinterpretations of valid python code.
**test**:
``` python
if True:
  print('ok')

print('ok without spaces in "empty" line')


if True:
  print('ok')
  
print('fails with spaces')


if True:
  print('ok')
print('fails without spaces')
```

**result**:
``` python
>>> if True:
...   print('ok')
... 
ok
>>> print('ok without spaces in "empty" line')
ok without spaces in "empty" line
>>> 
>>> 
>>> if True:
...   print('ok')
...   
... print('fails with spaces')
  File "<input>", line 4
    print('fails with spaces')
    ^
SyntaxError: invalid syntax
>>> 
>>> if True:
...   print('ok')
... print('fails without spaces')
  File "<input>", line 3
    print('fails without spaces')
    ^
SyntaxError: invalid syntax
>>> 
```

**Comment by realthunder** [comment]
Interestingly, this can actually be considered as a Python console bug, as you'll get the same error when pasting the same code to Python's built-in command line console. I have no idea why it hasn't been fixed for all these time.
