### ISSUE TITLE
sketcher always changes camera view

### ISSUE THREAD

**Issue by wohltat** [realthunder/FreeCAD#389]
Switching to sketcher always resets the camera view to an orthogonal view. Also leaving sketcher resets the view again.
As possible with other CAD software (e.g. Fusion360), i would prefer to choose not to change the view and visibilities. 
This would especially be useful when just editing some parameters of a sketch and seeing the implications in the resulting 3d model.
This is something that i regularly do and i have do manually every time.

![sketcher_always_changes_camera_view](https://user-images.githubusercontent.com/4751351/166160296-4b218bbc-d362-4ae1-a9f4-b7739a5bc378.gif)

I tried to emulate this behavior via python but it seems not possible. Actually it even seems not possible to recreate the normal behavior via python since there is some hidden code that is not logged to the console.

-------

Ideally there would be a new way to open the sketcher that doesn't change view and visibility. This could be accessed via Ctrl + double click on the sketch, or/and via context menu as the normal 'edit sketch' entry. Would also be nice

**Comment by wohltat** [comment]
something like this

https://youtu.be/KxlDsMQG7y4?t=292

**Comment by realthunder** [comment]
Implemented

![image](https://user-images.githubusercontent.com/1207888/167255749-6562259d-2d94-4d40-8dec-9958669f319d.png)
