### ISSUE TITLE
Box Selection

### ISSUE THREAD

**Issue by rgbertoni** [realthunder/FreeCAD#39]
Hi,

It is possible to make box selection via python? I mean, a function passing the screen coordinates and the freecad do selection inside the rectangle formed by the coordinates.
I searched in the forum, but as I'm using your branch I guess you could help me.
Anyway, thanks for your good work.

Regards.

**Comment by realthunder** [comment]
I have just exposed this functionality to Python. It will be available in next release. Sample usage:

```python
>>> Gui.ActiveDocument.ActiveView.Viewer.getPickedList([(200,200),(300,300)])
[(<Part::PartFeature>, 'Face1'), (<Part::PartFeature>, 'Face4')]
```

It can also do single point high level picking, e.g.

```python
>>> Gui.ActiveDocument.ActiveView.Viewer.getPickedList((764,255))
[(<Part::PartFeature>, 'Face1'), (<Part::PartFeature>, 'Shell1'), (<Part::PartFeature>, 'Solid1'), (<Part::PartFeature>, 'Face3')]
```

Its docstring is shown below

![Screenshot from 2020-08-07 20-56-34](https://user-images.githubusercontent.com/1207888/89648450-cdd18600-d8f1-11ea-9862-86b23e386348.png)

**Comment by rgbertoni** [comment]
Wow, great, thank you. This exactly what I need.
