### ISSUE TITLE
could not open files or folders from mounted disk

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD#397]
When navigating to a mounted disc or device, then it is displayed empty
![Screenshot from 2022-05-07 14-49-59](https://user-images.githubusercontent.com/76944804/167257363-39f78ddf-f819-44c6-b311-2097a8158fda.png)
![Screenshot from 2022-05-07 14-49-30](https://user-images.githubusercontent.com/76944804/167257367-6eb3e375-3094-485d-a5ef-3b386d8edb4d.png)

OS: Ubuntu Core 20 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 2022.505.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.05.05-2-edge)
Hash: 32adb43c3aa04846a3fb2b019f8efdfe3a06545f
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.1
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
I can't tell if this is LinkStage3 or LinkDaily ?

**Comment by mwlandolsi** [comment]
It is link daily installed from snap-store. This issue does not exist in .appimage version.

**Comment by luzpaz** [comment]
> It is link daily installed from snap-store. This issue does not exist in .appimage version.

CC @ppd
Hi! Any suggestions regarding accessing mounted disks with Snap ?

**Comment by ppd** [comment]
I'd check whether the removable storage devices permission has been granted in the software store thingy:

![image](https://user-images.githubusercontent.com/6652223/167293183-5ad87ea0-eabc-4148-9ae2-b3943691d447.png)

Or by terminal:

```shell
snap connect freecad-realthunder:removable-media
```
`

**Comment by luzpaz** [comment]
@mwlandolsi ping

**Comment by mwlandolsi** [comment]
Hello,
sorry to answer later, but it is not solved. 
Here is what I got after applying the command (terminal)

![Screenshot from 2022-05-10 20-47-15](https://user-images.githubusercontent.com/76944804/167710446-f02150f8-9393-40ec-ae3d-9de7da2a9ab0.png)

I do not know if this could help : 
Notice that I have set the "mount at system startup" option on.

![Screenshot from 2022-05-10 20-43-56](https://user-images.githubusercontent.com/76944804/167710451-c64eaaf8-a096-47dc-a99a-119f2380e043.png)

**Comment by ppd** [comment]
@mwlandolsi 
Could you please try the following:

```shell
# install snappy-debug
$ sudo snap install snappy-debug

# run snappy-debug in one terminal
$ sudo snappy-debug

# enter freecad-realthunder in a second terminal
$ snap run --shell freecad-realthunder

# in the second shell, navigate to your external disk
$ cd /home/xxx/Documents/discs/MyDocExt4

# execute some file accessing command, e.g. ls
$ ls -al
```

You should get some errors from `ls -al`, and, more importantly, you should receive some AppArmor errors from `snappy-debug` in the second terminal. Those errors can probably tell why access is being denied. 
Maybe it's about the UID & GID of the mount point within your home directory.

**Comment by mwlandolsi** [comment]
Hello Maximilian
I think you mean  the **first** terminal here :
> (...), you should receive some AppArmor errors from `snappy-debug` in the **second** terminal.(....)

Here what I got :


```
= AppArmor =
Time: May 12 10:20:43
Log: apparmor="DENIED" operation="open" profile="snap.freecad-realthunder.freecad-realthunder" name="/home/xxx/.bash_history" pid=19404 comm="FreeCADLink" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
File: /home/xxx/.bash_history (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* add 'personal-files (see https://forum.snapcraft.io/t/the-personal-files-interface for acceptance criteria)' to 'plugs'

= AppArmor =
Time: May 12 10:20:50
Log: apparmor="DENIED" operation="open" profile="snap.freecad-realthunder.freecad-realthunder" name="/home/xxx/Documents/discs/MyDocExt4/" pid=19404 comm="QFileInfoGather" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /home/xxx/Documents/discs/MyDocExt4/ (read)
Suggestion:
* add 'home' to 'plugs'
```

Me, and many other users,  are not good in Linux CLI ;) . So please if there is any suggestion, it will be helpful for the community.
Many thanks

**Comment by ppd** [comment]
@mwlandolsi 

from the denial, we can see:

>  fsuid=1000 ouid=0

This means that the mount point `/home/xxx/Documents/discs/MyDocExt4/` is owned by root. This is not allowed in the AppArmor profile:

https://github.com/snapcore/snapd/blob/bb08d2137f443c2169a095782fc0cfb33fb27d51/interfaces/builtin/home.go#L59

Therefore, I suggest either changing the owner of said directory & files (if that makes sense), or to mount it in `/mnt` or `/media/<user>` (or `/run/media/<user>`), where snapd is more tolerant wrt file ownership:

https://github.com/snapcore/snapd/blob/bb08d2137f443c2169a095782fc0cfb33fb27d51/interfaces/builtin/removable_media.go

The second variant is the way "it is supposed to be", I think.
