### ISSUE TITLE
Graphviz's path not found

### ISSUE THREAD

**Issue by gharkanyi** [realthunder/FreeCAD#398]
Hello!

Snap:
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 2022.505.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.05.05-2-edge)
Hash: 32adb43c3aa04846a3fb2b019f8efdfe3a06545f
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.1
Locale: English/United States (en_US)

It's not a blocker, mainstream problem, but the `Tools -> Dependency graph...` does not work, namely the `Graphviz`'s path is not found at all, although it is specified correctly in the parameters:
![Screenshot from 2022-05-08 15-56-42](https://user-images.githubusercontent.com/103138305/167299879-00142fd2-edc8-46f0-97ee-2d073da8ed41.png)
Anyway, the `Graphviz` works from command line, e.g. `$ echo 'digraph { a -> b }' | dot -Tsvg > /tmp/output.svg` is OK and:
![Screenshot from 2022-05-08 16-17-59](https://user-images.githubusercontent.com/103138305/167300591-2b6ca22f-0a7f-4256-a035-8e75d175af4f.png)

The FC's response:
![Screenshot from 2022-05-08 16-08-13](https://user-images.githubusercontent.com/103138305/167300135-4c5ab756-54d8-450e-b7b4-38264fe0d4a2.png)

Any idea?
Thank you in advance!

Bests
Gábor

**Comment by realthunder** [comment]
@ppd Any idea on how to launch external program from a confined snap app?

**Comment by ppd** [comment]
@realthunder not really possible aside from xdg-open. That's part of the security model. It's better to ship such dependencies in the snap itself.

**Comment by ppd** [comment]
Hm. Graphviz is already in stage-packages. Dot is located in `$SNAP/usr/bin/dot` which expands to `/snap/freecad-realthunder/current/usr/bin/dot`. We could set up a symlink in the mount namespace, so FreeCAD finds `$SNAP/usr/bin/dot` at `/usr/bin/dot`.

In any case, some additional configuration needs to be run for dot to find its plugins.

**Comment by ppd** [comment]
@realthunder Some graphviz fixes are here: https://github.com/ppd/freecad-ppd/commit/fe89c76ab238120fc3a5d2743c76b7312835dd1a

Let's see if that works out, and then we can integrate it into freecad-realthunder.

**Edit**: So dot works in `freecad-ppd` (I can render dot files to svg just fine). However, FreeCAD displays an error message:

> Graphviz failed to create an image file

There's some strangeness going on that'd need debugging. Unfortunately, it's all C++ and thus a bit to too time-intensive for me right now.

**Comment by luzpaz** [comment]
FreeCAD master Snap has been fixed in https://github.com/FreeCAD/FreeCAD-snap/commit/3b43c39b47e5311709b329f47e945f87733bd5b9

**Comment by luzpaz** [comment]
@gharkanyi please try again on latest edge

**Comment by gharkanyi** [comment]
Hi Guys!
Sorry for the somewhat late answer ...

Thank you very much, it WORKS now!
Thanks for yours works on this great project, go on in this way!

All the best!
Gábor
