### ISSUE TITLE
Fillet failed with order of selection of edges and faces (see video)

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD#406]
Here is a video showing the cases.
There are some cases that the fillet works and other cases that it does not.

https://user-images.githubusercontent.com/76944804/168583488-58ceb0c1-8ca7-45b0-9f33-78954c45abc8.mp4

[Uploading fillet 16-05-2022.FCStd.zip…]()

OS: Ubuntu Core 20 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 2022.512.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.05.12-edge)
Hash: 8f837b53c108a2444535be2604fdf31170dcf7f0
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United States (en_US)

**Comment by bambukouk** [comment]
I bet, that it is nothing to do with Link branch - if you tried the same exercise in master branch, the result would be exactly the same...

**Comment by mwlandolsi** [comment]
Hope to see this improvement in both branches.
