### ISSUE TITLE
issues with running test suite

### ISSUE THREAD

**Issue by ipatch** [realthunder/FreeCAD#413]
often after i build a version of freecad i run the below command to see if most or if not all things are working as they ought to be

```
./FreeCAD.app/Contents/MacOS/FreeCAD -t 0
```

unfortunately, (different from the freecad/freecad upstream counterpart) this test suite prompts me for ($USER) input to recompute several objects several times.

1. is it not possible to run the test suite and have it complete without user input?
2. i got some interesting test suite failures that i have not seen before, the error messages can be see in the attached file.

[fc.ls3.test.0.results.txt](https://github.com/realthunder/FreeCAD/files/8709581/fc.ls3.test.0.results.txt)

---

i've also added two screengrabs of the freecad interface when running the above test suite and when it prompts me for user input.

![image](https://user-images.githubusercontent.com/613805/168850414-cbf4e97e-0795-4924-ad75-3dd3ab2d8c55.png)

![image](https://user-images.githubusercontent.com/613805/168850519-08ab6ff8-0c28-4723-83ae-13d94bdedb37.png)

**Comment by realthunder** [comment]
You can turn off this prompt wit `Preferences -> General -> Document -> Prompt recomptutation after loading legacy document`.
