### ISSUE TITLE
Open FreeCAD file using "open with" option - doesn't work

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD#424]
Snap version, as per forum post:
https://forum.freecadweb.org/viewtopic.php?f=42&t=65662&p=597126#p597098
![image](https://user-images.githubusercontent.com/50301871/170019019-8b2338b9-7f36-4353-8d67-efc50ab9d8eb.png)
![image](https://user-images.githubusercontent.com/50301871/170019049-f1b2d99b-8602-42da-8c54-d8f777181528.png)

Problem is caused by `%F` missing from .desktop file
adding it solves the problem:
![Screenshot from 2022-05-24 11 57 41](https://user-images.githubusercontent.com/50301871/170019566-4158cef2-aede-4ad6-8eba-f34978b7fafb.png)
```
OS: Ubuntu Core 20 (Pantheon/pantheon)
Word size of FreeCAD: 64-bit
Version: 2022.520.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.05.20-edge)
Hash: d47fafeec334a1069256639f391f17368276068c
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United Kingdom (en_GB)
```

**Comment by luzpaz** [comment]
Want to make a PR ? :smirk:

**Comment by bambukouk** [comment]
> Want to make a PR ? smirk

It works fine in master branch... 
I am suggesting it needs to be corrected in Link branch so it also works OK out of the box.
One wouldn't expect to have to mess with innards of snap?
It only works for me because I use copied .desktop (outside of snap) and modify it myself to customise integration in OS.
as for PR... I don't even know what it is :+1:

**Comment by ppd** [comment]
The desktop file for the realthunder snap should be this one: https://github.com/realthunder/FreeCADMakeImage/blob/master/conda/branding/asm3/AppDir/freecad_link.desktop

This snap differs from the official one because it uses a separate repo and install script to inject the FreeCAD Link Branch branding. That's why there's a difference in behavior.

**Comment by bambukouk** [comment]
thank you @ppd 👍
