### ISSUE TITLE
macOS: Quit menu item always disabled + shortcut 'command + q' to quit isn't recognized 

### ISSUE THREAD

**Issue by horfee** [realthunder/FreeCAD#433]
Hi,

Quit menu item from the "FreeCAD Link Daily" menu is always disabled, even if there are no file opened or created.
The shortcut ("Command+Q") is not working ; the only way to exit FreeCAD is to click on the red bubble on the top left corner of the window (this works fine).

I am running : 
OS: macOS 12.3
Word size of FreeCAD: 64-bit
Version: 2022.407.26244 +4693 (Git)
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.9.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: C/Default (C)

**Comment by luzpaz** [comment]
Can you recreate on LinkDaily?

**Comment by horfee** [comment]
Reproduced on this release (the latest available) : 

OS: macOS 12.3
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git)
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: C/Default (C)

**Comment by bambukouk** [comment]
Is this the same as `Exit (Alt+F4)` ??
I guess it must be mac specific?

my version:
```
OS: Ubuntu Core 20 (Pantheon/pantheon)
Word size of FreeCAD: 64-bit
Version: 2022.527.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.05.27-edge)
Hash: 39c9a013e168a7ebb2f8cb2241de144bb0b20b5d
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United Kingdom (en_GB)

```

**Comment by horfee** [comment]
Command+Q is the same as Alt+F4 on windows you are right.
This is the standard shortcut for terminating any app on a mac.

**Comment by bambukouk** [comment]
OK, I shall leave it to you mac boys :+1:

**Comment by axwnet** [comment]
works fine for me

**Comment by luzpaz** [comment]
Closing. Please re-open if persists
