### ISSUE TITLE
AppImage crash on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by risacher** [realthunder/FreeCAD#435]
If I try to run the appimage for "daily 20220430" or "stable 20220430" or "daily 20220111" on my Ubuntu laptop (22.04 LTS "Jammy Jellyfish"), the splash screen shows, but it crashes before the main window opens (console log below).  

The snap for 'freecad-realthunder' (dated 2022-05-27) works fine on the same machine. 
The appimage for daily 20220111 worked before I upgraded Ubuntu from 20.04 LTS.   

```
magnus@akond:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
magnus@akond:~$ bin/FreeCAD-asm3-Daily-Conda-Py3-Qt5-20220430-glibc2.12-x86_64.AppImage 
/tmp/.mount_FreeCATkxCR3
FreeCAD 0.20, Libs: 2022.430R26244 +4758 (Git)
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/tmp/.mount_FreeCATkxCR3/AppRun: line 46: 1747639 Aborted                 (core dumped) "$PREFIX/bin/$name" "$@"
```

**Comment by realthunder** [comment]
Check check issue #390 and try the workarounds there.

**Comment by risacher** [comment]
Thanks for the tip. I did try to look for similar issues but I guess I didn't search on the right terms. 

The machine has an iris graphics chip.  `MESA_LOADER_DRIVER_OVERRIDE=i965` will cause the 20220430 appimage to run for me, but the "Start Page" is solid black. If I load an existing project though, it seems to work fine. (Have not tested extensively.) 

Alternatively, adding `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6` will also cause FreeCAD to start from the appimage, presumably with the correct driver for my machine (iris_dri.so).  I believe iris_dri.so wasn't loading because the version of libstdc++ packaged with the appimage didn't match the version required by Ubuntu 22.04's version of iris_dri.so. 

In this case, the "Start Page" is also black, so that's not just an issue with running the wrong graphics driver.  On the other hand, I don't really care about the "Start Page" and I don't want @realthunder to waste a single additional minute on this.  I back you on Patreon for the important work you do fixing things like the topo naming problem; not annoying library packaging nonsense.  Thanks for the help and thanks again for all you do.
