### ISSUE TITLE
[Feature Request] Sketcher copy/paste (via xml) included in Link branch (see upstream PR)

### ISSUE THREAD

**Issue by derMart** [realthunder/FreeCAD#452]
Hey, it seems the very useful feature of generic copy paste sketcher geometries in between different sketches, even in between different instances of freecad (see here: https://www.youtube.com/watch?v=ZH432giUasM) is not working in this fork.
If I select a portion of a sketch inside sketcher, the Edit -> Copy menu is greyed out.

I am using FreeCad Link Branch daily snap package (Version 2022.617)

**Comment by derMart** [comment]
oh dear just realized this is not even merged in 'normal' FreeCad. This is very useful, so I would like to add this feature in this fork as feature request please!

**Comment by luzpaz** [comment]
You're referring to the open PR in upstream, right? https://github.com/FreeCAD/FreeCAD/pull/5480

**Comment by derMart** [comment]
Yea, sorry, I just found out about that pull request. Probably better to merge it upstream.
EDIT: Which I highly recommended (would also be willing to look at its current issues)

**Comment by luzpaz** [comment]
@derMart feel free to participate in the discussion thread associated with that issue. I think for now, we should close this ticket until upstream adds it? Don't you think? Since Realthunder has is dealing with toponaming and other issues right now.

**Comment by derMart** [comment]
sure, you are right
