### ISSUE TITLE
Strange behavior when freezing assembly

### ISSUE THREAD

**Issue by alowell-ssl** [realthunder/FreeCAD#453]
I'm noticing something strange when freezing an assembly in A3 workbench.  Before freezing, I see this:

![image](https://user-images.githubusercontent.com/25305416/174511139-ecc34868-7dee-4737-abc8-debdca49903d.png)

Right clicking the assembly in the tree and clicking "Freeze assembly", I see this:

![image](https://user-images.githubusercontent.com/25305416/174511217-f8d63368-9ae3-4782-b2ca-94e09e78d8d9.png)

After the assembly is frozen, if I click on the "top" part under "walls" in the tree (like in the first image), FreeCAD selects some spurious geometry that I didn't model:

![image](https://user-images.githubusercontent.com/25305416/174511341-3550addc-c350-47e9-aa28-e8d792476b9e.png)

I'm kind of a noob at the Assembly workbenches, so maybe I'm doing something wrong? Here is the file:

https://drive.google.com/file/d/18UKJqvJYCVH3RkXG_txwnScIUD_lvIQp/view?usp=sharing

**Comment by realthunder** [comment]
The above commit should fix the problem. BTW, are you building my branch yourself, or using the latest snap version? Next time, please paste the `Help -> About` information here. Thanks

**Comment by alowell-ssl** [comment]
Wow that was fast, thanks! I was using the snap package:

OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 2022.618.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.06.18-edge)
Hash: bd42d5caa247c98b4214b5e535133bdbd4e78d56
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United States (en_US)
