### ISSUE TITLE
polyline Modifier did not work in newest version

### ISSUE THREAD

**Issue by yahbluez** [realthunder/FreeCAD#496]
The M modifier for polylines is not available in the version from 9.7.2022

**Comment by realthunder** [comment]
Upstream has refactored keyboard shortcuts for Sketch workbench. You can assign your own using `Tools -> Customize -> Keyboard`

![image](https://user-images.githubusercontent.com/1207888/178627737-f3463749-c8bf-437a-9dec-febb3019f818.png)

**Comment by yahbluez** [comment]
The shortcut is still set to G,M but didn't work anymore. I can select a polyline but i can not change the behavior with G,M. In versions before 709 it worked as expected.

**Comment by Shkolik** [comment]
Works fine with G,M on:
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.709.26244 +5001 (Git)
Build type: Release
Branch: LinkDaily
Hash: 096210d21183e9dfdc3b25777760bfb6c00a210b
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United States (en_US)

**Comment by yahbluez** [comment]
2022.716 the bug is gone!

In two previous version even when i changed the key it didn't work.

On the same system the vanilla version(s) did not show that bug and older RT version ether.

**Comment by yahbluez** [comment]
.
