### ISSUE TITLE
Manjaro/Arch linux build failure

### ISSUE THREAD

**Issue by obelisk79** [realthunder/FreeCAD#50]
Issue building on Manjaro/Arch linux:
main FreeCAD/FreeCAD branch builds ok
LinkStage3 fails.

Builds ok on Win10 not on linux
cmake error log attached
[CMakeError.log](https://github.com/realthunder/FreeCAD/files/5305248/CMakeError.log)

This may be a dependency related issue, although I have triple checked all dependencies appear to be installed in accordance with the guidelines set forth here: https://wiki.freecadweb.org/Compile_on_Linux

**Comment by realthunder** [comment]
Can you please post the complete console output?

**Comment by obelisk79** [comment]
I'm building right now, and I think I corrected the issue by adding:
`
#include <QPainterPath>`

to /src/Gui/OverlayWidgets.h
I'll report once complete, currently at 95% build status

**Comment by obelisk79** [comment]
Confirmed, adding the include statement corrected the build problem. Unsure why I was able to build on Win10 but not linux without it.

**Comment by obelisk79** [comment]
I believe unrelated, but I get the following in console when I run FreeCAD. I can open as a separate issue if you want. The coin errors occur when I enable shadows in viewport.

[obelisk79@obelisk79-manjaro bin]$ ./FreeCAD
FreeCAD 0.19, Libs: 0.19R25101 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2020
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.

<Command> Command.cpp(1839): duplicate command Std_TreePreSelection
<Command> Command.cpp(1839): duplicate command Std_TreeSelectAllInstances
connect failed: No such file or directory
Coin info in SoGLSLShaderObject::printInfoLog(): GLSLfragmentShader  log: '0:67(1): error: no function with name 'DirectionalLight'
'
Coin error in SoGLSLShaderProgram::ensureLinking(): error: 'GL_INVALID_VALUE' (set envvar COIN_GLERROR_DEBUGGING=1 and re-run to get more information)

**Comment by realthunder** [comment]
Not sure why you got the `duplicate command` warning, but that's not fatal.

The `GLSLfragmentShader` error is due to an older `libCoin` which means that shadow rendering won't work. If you really want the shadow, you'll have to download [Coin3D](https://github.com/realthunder/coin) source code and compile it yourself. You'll also need to compile pivy as well.

**Comment by obelisk79** [comment]
Understood, thank you for the response.
