### ISSUE TITLE
Display Style Settings Overwritten

### ISSUE THREAD

**Issue by master-puller** [realthunder/FreeCAD#503]
When I attempt to change the display styles for selection to disable transparent overlay of object, settings do not save and are restored to default. This happens only on the `Display > Draw Styles > Hidden Lines` submenu.
I am attempting to turn off transparency on selection, yet this issue does not allow it. Video below of the bug in action

https://user-images.githubusercontent.com/19511301/179030915-30a1bda6-7a1b-4635-bf07-7b7e60f5b97a.mov

**Comment by master-puller** [comment]
I found the solution to my previous problem, but the bug is still there which blocks those settings.

**Comment by realthunder** [comment]
The option you want to turn off is called `Selection on top`. It is a selection behavior option, not relevant to draw styles. You can use shortcut `V, T` to toggle the option.

![Screenshot from 2022-07-15 06-21-08](https://user-images.githubusercontent.com/1207888/179098298-5bfcebb5-5856-4ca7-bc16-5bb42d08ca5f.png)

**Comment by master-puller** [comment]
So, Even with Selection on top disabled, you cannot apply any of the Hidden Line override colors

**Comment by realthunder** [comment]
Hidden Line override is only applicable if you set the draw style to hidden line, but your screen recording shows you are using the shadow draw style.
