### ISSUE TITLE
SNAP webpage broken link because a missing letter

### ISSUE THREAD

**Issue by MiqCG** [realthunder/FreeCAD#509]
In Snap web page https://snapcraft.io/freecad-realthunder
when it says " This is an unofficial package. Please report issues at https://github.com/realthunder/FreeCAD/issue "
the link is broken (404 error) because the final "S" is missing:
--> https://github.com/realthunder/FreeCAD/issue**s**

By the way, funny loop with an issue in the reporting issues link ;-)

Thanks for your intense work

**Comment by realthunder** [comment]
Thanks for the heads up. I just edited the link, but somehow snap listing page didn't update. Maybe have to wait till next build release.

**Comment by MiqCG** [comment]
Good, it is yet updated.
