### ISSUE TITLE
[BUG] UI element positioning not saving

### ISSUE THREAD

**Issue by obelisk79** [realthunder/FreeCAD#52]
Good Afternoon,

When I open a document, or restart FreeCAD some UI  elements are not restored to their previous positioning. On the right side of the screen you can see what I am referring to. I slide the combo window to hide the tree, and move the viewport cube to the left of the combo view panel.

Here is what it looks like when reopening each document:
![start](https://user-images.githubusercontent.com/17993710/95687973-cb7ef700-0bd4-11eb-84d6-1cc483254707.png)

Here is what I repeatedly set up my view to look like:
![setup](https://user-images.githubusercontent.com/17993710/95687982-e2bde480-0bd4-11eb-9267-cd811262ebd7.png)

**Comment by realthunder** [comment]
I'll fix that.

BTW, combo view with model and task is probably going to be obsoleted in the future. I can't think of any real use case of two tree view, just waste of resources. If you want a split property and tree view, you can set the tree view mode in preference dialog as 'Tree view and property view'. And you'll get a stand alone property view that you can move around independent of task view. Just dock it together with the task view if you want. The inside panels of combo view are not controlled by overlay manager.

**Comment by obelisk79** [comment]
Thanks for the info!
