### ISSUE TITLE
Add version information to AppImages

### ISSUE THREAD

**Issue by TheAssassin** [realthunder/FreeCAD#558]
Currently released AppImages do not contain a version number usable by the AppImage desktop integration. Unfortunately, this can lead to problems when using multiple releases in parallel: they are all listed under the same name in the app menu and cannot be distinguished from each other. Some software like AppImageLauncher can at least improve the situation by appending numbers (e.g., `(1)`, `(2)`). The real solution however is to append version numbers.

appimagetool can do this easily for you, you just need to `export VERSION=...` with some meaningful value. Then, we can have `FreeCAD Link Branch (2022.07.09)` next to `FreeCAD Link Branch (2022.04.30)` for instance.

Unfortunately, the code to build AppImages is not located in this repository, otherwise I may have sent a PR.

**Comment by luzpaz** [comment]
@realthunder the appimage creation happens in https://github.com/realthunder/FreeCADMakeImage or https://github.com/realthunder/AppImages ?
