### ISSUE TITLE
Feature request: add 3D sketch rotation

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#569]
Original Freecad has free sketch rotating in 3D. It's really handy option, it would very good to merge this from original branch.

**Comment by realthunder** [comment]
I am not sure what do you mean by 'free sketch rotating in 3D'. Can you please post a screen cast?

**Comment by vovodroid** [comment]
While you are in sketcher you can rotate it together in all directions with the whole body as on any other screens:

![image](https://user-images.githubusercontent.com/8691781/193523485-61f846a8-227c-4ac0-bad3-19b252a7ee43.png)

**Comment by realthunder** [comment]
Try holding 'Alt' key and then do the rotation?

**Comment by vovodroid** [comment]
Indeed, thank! Actually I looked for navigation style without Shift-Alt modifiers. In original FreeCad I use Tinkercad style, and here I found Gesture style.

Could it be customized in preferences?

**Comment by realthunder** [comment]
Unfortunately, no. The navigation style needs a lot rework for that to happen

**Comment by discip** [comment]
@vovodroid
It seems that your initial problem has been solved.
Please don't forget to close it. 😊
