### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by discip** [realthunder/FreeCAD#573]
@realthunder

FreeCAD is already a great piece of software in its own right and most of us (CAD users) liked the fact that it is already reasonably capable, although the learning curve is relatively steep.

# But you Sir have taken this software to a whole other level! 🤯
# THANK YOU VERY MUCH! 👍

ps:

I really would like to test the latest state of your work. Preferably for win10, but I also could do this on a linux machine.
Which way do you recommend me to go?

Thanks in advance kind regards

**Comment by Neubo** [comment]
Hello,

RealThunder  will release soon a new win10 version. But if you want to test the most recent versions, consider the snap version :

https://snapcraft.io/freecad-realthunder

PS : I totally agree with you about Freecad / RealThunder improvments !

**Comment by luzpaz** [comment]
Thanks for feedback. 
Snap 'edge' builds are the way to go (generated nightly)  

Closing ticket.
