### ISSUE TITLE
"Shadow" display/render style appears broken

### ISSUE THREAD

**Issue by scottmudge** [realthunder/FreeCAD#592]
# Description

Perhaps this is a known issue as the change to the renderer is being worked on, but I've noticed for the last couple months (didn't really check before that, perhaps the issue goes back farther) that the "Shadow" render mode is pretty broken.

I've noticed:

1. It is completely flat and lacks all shading.
2. Switching to "shadow" resets the camera orientation to an isometric position, whereas the other render modes do not.

**Build:** 2022.10.16-2-edge
**OS**: Windows 11

# As-Is Render:
 
![image](https://user-images.githubusercontent.com/19617165/196197963-9abdcc29-d6b0-4e10-bf36-0c0fe42ead23.png)

# Shadow Render:

![image](https://user-images.githubusercontent.com/19617165/196198014-cd46bc9c-b2bc-404b-977d-143bca0acb09.png)

# Settings:
![image](https://user-images.githubusercontent.com/19617165/196198514-9a8e63ff-7dcd-471d-8be2-390785ff050e.png)
![image](https://user-images.githubusercontent.com/19617165/196198566-d19f5b08-eeda-4639-8262-890e3cbf4e04.png)

**Comment by realthunder** [comment]
Can you please send me you user settings. `Tools -> Edit parameters -> Export`.

**Comment by scottmudge** [comment]
[my_params.zip](https://github.com/realthunder/FreeCAD/files/9801795/my_params.zip)

Attached

**Comment by realthunder** [comment]
I can't reproduce the problem with your setting. Can you please double check the revision number of you local repo. Maybe try a fresh user settings and see.

**Comment by realthunder** [comment]
And also please check if you are using my forked libCoin.

**Comment by scottmudge** [comment]
> And also please check if you are using my forked libCoin.

That was it. Recompiled your fork and it works now. Thanks!
