### ISSUE TITLE
invalid subname. What does it mean ?

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#594]
![invalidSubname](https://user-images.githubusercontent.com/12879321/196378105-9ad661da-3ac7-4bc6-bce0-fcb6420f8486.png)

I get this error every time I am updating a spreadsheet containing a few design parameters. It seems anyway that the geometry is properly updated.

**Comment by realthunder** [comment]
It is from some external workbench, or Macro. Can you please search your `.FreeCAD` directory for this FCvarUpdate.py file and let me know which workbench/Macro it belongs.

**Comment by wsteffe** [comment]
The macro (here annexed) is just copying values from an external csv file with same name as FC document name +"_var" suffix into the internal Spreadsheet named "Variables".
[FCvarUpdate.zip](https://github.com/realthunder/FreeCAD/files/9809326/FCvarUpdate.zip)

I do not think that the "inavlid subname" can be related with this macro. But it is also true that the error is not displayed if I make a simple recompute without changing any variable/parameter.

**Comment by realthunder** [comment]
Is it possible to share your file?

**Comment by wsteffe** [comment]
yes sure:
[CoaxFilt_7_2_doubleSymmetry.zip](https://github.com/realthunder/FreeCAD/files/9811453/CoaxFilt_7_2_doubleSymmetry.zip)

**Comment by realthunder** [comment]
I can't seem to reproduce the problem. I used FCvarUpdate for updating the parameters but no warning message. Can you please describe your workflow. Maybe also post your settings here `Tools -> Edit prarameters -> Export`.

BTW, make sure you build is synced to my branch.

**Comment by wsteffe** [comment]
Hi RT, here are my parameters:
[myparam.zip](https://github.com/realthunder/FreeCAD/files/9819357/myparam.zip)
Looking at those parameters you may also perhaps tell me why I can't see the mapped name (but just a simple name such as Face1) when I select a 3d object. 

My build was synced with 0a9e2bbf71086f54d67319b0879ba73bd1c9380b. But I have just started to build with last commit (a3d793869825443b46d981707dbdbe8b8d72b168).

**Comment by wsteffe** [comment]
Sorry RT. I have just seen that I sent the wrong FC file.
This was the file producing the error message [CoaxFilt_7_2_v7.zip](https://github.com/realthunder/FreeCAD/files/9819493/CoaxFilt_7_2_v7.zip)

**Comment by wsteffe** [comment]
To complete the data I am annexing also the unmodified csv file:
[CoaxFilt_7_2_v7_var.csv](https://github.com/realthunder/FreeCAD/files/9819505/CoaxFilt_7_2_v7_var.csv)

To reproduce slightly change a variable and then execute FCvarUpdate.py.
