### ISSUE TITLE
Wrong external geometry link

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#598]
Though for BackSupportPad (Sketch007) external edge of PlatePad (Pad) is chosen it's linked to BackPad (Pad0001)
![image](https://user-images.githubusercontent.com/8691781/197254034-fe2848c3-2dce-48d2-aa15-55878d735e8f.png)

May be it causes #595 
[DirectBack.zip](https://github.com/realthunder/FreeCAD/files/9841147/DirectBack.zip)

**Comment by realthunder** [comment]
How did you select the reference? You are supposed to manually unhide `Pad` and then select the edge. FreeCAD feature contains all the geometry from previous features.

**Comment by vovodroid** [comment]
> How did you select the reference?

I don't remember. Just saw that I can't move Pad0001 because it has dependency, and found, that external edge linked to wrong object (though visually it's in right place).
