### ISSUE TITLE
Sketcher external geometry tool doesn't work anmore

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCAD#60]
Since commit _1453b094363d8e4a196735f4fbd39b6d650e715b_ the sketcher external geometry tool doesn't work anymore. I've tried the git history before and after this commit and can reproduce the behaviour.

**Comment by realthunder** [comment]
Should be fixed now. I'll update the release soon.

**Comment by dulouie** [comment]
By the way, do you know this post?
https://forum.freecadweb.org/viewtopic.php?f=10&t=51716
