### ISSUE TITLE
PartDesign Chamfer distance&angle doesn't work

### ISSUE THREAD

**Issue by m-sundman** [realthunder/FreeCAD#606]
Chamfer using a distance and an angle doesn't work in PartDesign. (It works with one or two distances.)

OS: Ubuntu 22.04.1 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 2022.1021.26244 +5249 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: d307b5c936403e8dca3f24b5c1e64bd16c88b28d
Python version: 3.9.13
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Can you please post a file showing the problem? I can't seem to reproduce the problem.
