### ISSUE TITLE
It's hard to edit "internal faces" after pad/pocket creation

### ISSUE THREAD

**Issue by pgilfernandez** [realthunder/FreeCAD#608]
First of all, thank you very much for this AWESOME feature, it's a game changer and a incredible workflow speed up, thank you!

A very common situation is that you change your mind about the "internal faces" you want to select for a pad/pocket and want to go back and edit them... with this first release it's kind of difficult (or hidden) how to do it. It would be nice to have an easy way to do it (probably a button inside the pad/pocket task panel).

In the meantime, I found out that going to Data/Sketch based/Profile and pressing in the "..." button lets you go to a popup window where you can edit them. The problem is that the window doesn't stay on top to let you select and check your new selection. A workaround is to push "clear" button and select the new "internal faces" or even make room to this pop up windows by shrinking your main window... They work but, UX speaking, it's not something that should be left like this.

Thanks again for your work!!
Cheers

**Comment by realthunder** [comment]
I just implemented this in 1aa10e73e
