### ISSUE TITLE
"Make Internals" feature creating broken geometry

### ISSUE THREAD

**Issue by herrgerd** [realthunder/FreeCAD#623]
Hey Lei,
I wanted to try your newly added feature.
Created two slots and used this sketch to extrude it in both directions of the plane.

When "refine" is active, it works. If not, it creates something like this:

![grafik](https://user-images.githubusercontent.com/24494466/199304831-e0bbaa14-9f1a-4b6e-8700-654ac7eb8177.png)

Cheers, Jan

OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 2022.1021.26244 +5249 (Git)
Build type: Release
Branch: LinkDaily
Hash: d307b5c936403e8dca3f24b5c1e64bd16c88b28d
Python version: 3.9.13
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: German/Germany (de_DE)

[error.zip](https://github.com/realthunder/FreeCAD/files/9912842/error.zip)

**Comment by realthunder** [comment]
The error seems just went away by simply do a recompute. Note that you'll need to recompute the first Pad. Can you remember you steps to reproduce the error?

**Comment by herrgerd** [comment]
> The error seems just went away by simply do a recompute. Note that you'll need to recompute the first Pad. Can you remember you steps to reproduce the error?

Tried it, did work but only after manually recomputing each pad. I guess I'll close this thread now.
