### ISSUE TITLE
STL export

### ISSUE THREAD

**Issue by ljungis** [realthunder/FreeCAD#624]
I have designed this body and exported it as an .stl file.
However all the slicers I have tried says it is not a valid stl file.
I have tried Cura, Prusa and Ideamaker.
What is wrong?

[Valve_test.zip](https://github.com/realthunder/FreeCAD/files/9928579/Valve_test.zip)
[Valve_test-Body.stl.zip](https://github.com/realthunder/FreeCAD/files/9928580/Valve_test-Body.stl.zip)
![Uploading Screenshot.png…]()

**Comment by herrgerd** [comment]
If you mark the last entry in the object tree and then export, it does work. It's a quirk I encountered several times.
![grafik](https://user-images.githubusercontent.com/24494466/200684360-8043ea22-5631-49f5-897a-5ee35070b551.png)

This is btw. a very useful feature to export different "stages" of your model to see where things go sideways when fighting with broken models...


[Valve_test-BodyPad002.zip](https://github.com/realthunder/FreeCAD/files/9965546/Valve_test-BodyPad002.zip)

**Comment by ljungis** [comment]
Thank you Jan. This solved it.

Den tis 8 nov. 2022 22:58Jan ***@***.***> skrev:

**Comment by discip** [comment]
@ljungis
Please don't forget to close this issue if solved.

**Comment by ljungis** [comment]
Thank's.
