### ISSUE TITLE
how to donate to respect your time and effort to bring FreeCad to this level

### ISSUE THREAD

**Issue by pbk85** [realthunder/FreeCAD#625]
It's not really an issue, 

but I could not find any ko-fi or paypal or whatever to honor your great project and keep you motivated to continue.

**Comment by herrgerd** [comment]
https://www.patreon.com/thundereal

**Comment by pbk85** [comment]
Thank's @herrgerd 

I donate € 50 and quit the membership then --> I hate SAS and patreon is a sort of...

**Comment by herrgerd** [comment]
Yep, but that's what we got to help him and other creators... I am a regular donator as well. Lei is also on https://en.liberapay.com/realthunder btw.

I just wanted to kill my Patreon-Support and switch to Liberapay but something went wrong. @realthunder I will repair that as soon as possible :)

**Comment by realthunder** [comment]
@pbk85 Thank you very much for your support!
