### ISSUE TITLE
Nodes addon doens't work with snap version

### ISSUE THREAD

**Issue by czinehuba** [realthunder/FreeCAD#644]
It gives a qtpy missing error if we try to run on the snap version. 

It works with the version installed on the system.
![image](https://user-images.githubusercontent.com/48809015/203791287-3e0fc70a-a29a-47fc-af64-3c68158732da.png)

OS: Ubuntu Core 20 (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 2022.1120.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.11.15-edge)
Hash: d18dbf08841c51a61705a591ff87bf465c193495
Python version: 3.8.10
Qt version: 5.15.5
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United Kingdom (en_GB)

**Comment by axwnet** [comment]
Same problem occurs on macOS. (pyqt is installed with brew but not acessible by freecad)
"awkward" is also needed for it to work as intended (see my comment https://github.com/realthunder/FreeCAD/commit/ef2a0c326eea5325952b4059d6e5ea5eca6a47fb)
