### ISSUE TITLE
Pocket generates odd/wrong geometry after modifying pocket

### ISSUE THREAD

**Issue by andyylin** [realthunder/FreeCAD#645]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 2022.1112.26244 +5306 (Git)
Build type: Release
Branch: LinkDaily
Hash: c64e4a49244a1c0ce9fd6455d18aa919d0db9c80
Python version: 3.10.6
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: C/Default (C)

I'm not expert enough to understand the underlying issue here, so in very plain terms the pocket that runs through the hinge used to work fine, but after adding a 0.1mm tolerance the entire geometry goes crazy:

![image](https://user-images.githubusercontent.com/51783311/203879922-e78e6116-288e-4319-a4ac-f027a1626c40.png)

Here's the original file before changing the tolerance.
[供料機案件蓋子-switch-cover.zip](https://github.com/realthunder/FreeCAD/files/10087869/-switch-cover.zip)

Here's the file after just modifying the pocket tolerance to 0.1mm:
[供料機案件蓋子-switch-cover-error.zip](https://github.com/realthunder/FreeCAD/files/10087870/-switch-cover-error.zip)

Here's the file after trying to change the tolerance back to 0.1mm. The odd geometry remains:
![image](https://user-images.githubusercontent.com/51783311/203880462-ff61edfc-fa5c-4937-8eb8-df50e22458ee.png)
[供料機案件蓋子-switch-cover-error2.zip](https://github.com/realthunder/FreeCAD/files/10087874/-switch-cover-error2.zip)

----

As another reference, the same file also ran into a pocket issue that originally worked but after modifying a previous sketch, no amount of adjustment would cause the pocket (Pocket006) to work properly again.
![image](https://user-images.githubusercontent.com/51783311/203880659-cee392c6-8bfd-4f8d-894f-79d6ac2eccb7.png)
[供料機案件蓋子-switch-cover-error3.zip](https://github.com/realthunder/FreeCAD/files/10087882/-switch-cover-error3.zip)

----
I've tried recomputing each step to see if the problem goes away, but that doesn't help either.

**Comment by realthunder** [comment]
This kind of weird shape usually mean that there is some error in early modeling step. For your case (the first attached file), it is the `PocketBase` as shown below

![image](https://user-images.githubusercontent.com/1207888/204079667-b354d038-fa79-45cf-aa0d-b4e5a2f1da9f.png)

I've been seeing this kind of failure popping up more frequently lately. I am not sure what's the actual cause. Please right click the document icon in the tree view and select `Mark to recompute` to mark all objects for recompute. A complete recompute can fix the potential problem in your first file. For your later files, a full recompute is still required. But there will be more errors require manual fixes.

**Comment by andyylin** [comment]
I've updated to the latest Edge:

OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 2022.1128.26244 +5318 (Git)
Build type: Release
Branch: LinkDaily
Hash: d45d221edcc7a757eb4e4eb638da0db5ed2759aa
Python version: 3.10.8
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: C/Default (C)


Marking the document to recompute and recomputing didn't fix the issue. I still had to manually recompute each step to eliminate the errors. 

But at the end, after all the recomputes, adding this pocket still causes an issue:

![Tree](https://user-images.githubusercontent.com/51783311/206110918-9a7fef26-e660-4241-8d8e-dcfc007cd15b.jpeg)

![Pocket_error](https://user-images.githubusercontent.com/51783311/206110938-3c49c089-394c-44fe-9450-d8afdbe1e2b0.jpeg)

Here's the updated file.
[供料機案件蓋子-switch-cover.zip](https://github.com/realthunder/FreeCAD/files/10173583/-switch-cover.zip)

**Comment by realthunder** [comment]
Judging by the look of the shape, it indicates that there are errors in your model history. Here is a simple trick to find out which one. Just use the `Check geometry` command button on each early feature starting from the one have the problem and going backward. You need to select the feature first before this button gets activated.

You can trace out that the first feature having some error is `PocketBase`. And it looks like an common OCC (the CAD kernel) tolerance problem. The `UpToFace` option you use produce a cutting tool shape at a critical height which confuses OCC. Using a slight offset to make it just a little bit taller can solve all your later problem.

![image](https://user-images.githubusercontent.com/1207888/206862006-505216b3-b4d9-429d-8c4e-fab2d045e1ea.png)

![image](https://user-images.githubusercontent.com/1207888/206862068-f300c704-c4b7-4201-a34e-0f8bbe42f513.png)

**Comment by andyylin** [comment]
Wow, thank you, now I know how to troubleshoot this problem in the future. 

If there was a way to hint to the user what the error is related to, I think it would help more beginners like myself adopt FreeCAD use.

Thanks again, closing the case.

**Comment by realthunder** [comment]
I have added an option to auto validate shape on changes. See [here](https://github.com/realthunder/FreeCAD/issues/662#issuecomment-1356738217) for a demo.
