### ISSUE TITLE
Access violation on cancel button

### ISSUE THREAD

**Issue by marvinmz** [realthunder/FreeCAD#648]
I am consistently getting access violation when pressing the cancel button on the pad and pocket tools in part design.

Steps to recreate:

- in Part Design create a new sketch on the slanted face
- create a rectangle inside the face
- use the pocket tool on the newly made sketch
- select the cancel button

[dummy.zip](https://github.com/realthunder/FreeCAD/files/10112926/dummy.zip)

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1112.26244 +5306 (Git)
Build type: Release
Branch: LinkDaily
Hash: c64e4a49244a1c0ce9fd6455d18aa919d0db9c80
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/Slovenia (en_SI)


```

**Comment by realthunder** [comment]
I can reproduce the problem in 11.12 release, but it seems gone in the latest 11.28 release. Please try and report back.

**Comment by marvinmz** [comment]
I am still getting the same error. Is there a way to get a stack trace or something else that would be helpful?

**Comment by realthunder** [comment]
It is in user FreeCAD user directory, usually `C:\Users\<username>\AppData\Roaming\FreeCAD\crash.log`. I've seen mine. It crashes in Coin3D. I am not quite sure exactly where nor why.

**Comment by realthunder** [comment]
I've found a problem that most likely is the culprit. Feel free to reopen if you still experience any problem.
