### ISSUE TITLE
Zooming with scroll wheel doesn't work

### ISSUE THREAD

**Issue by rgbertoni** [realthunder/FreeCAD#65]
Hi, I'm facing this issue when I compiled last night in my arch linux: https://forum.freecadweb.org/viewtopic.php?f=3&t=50231&start=40
So, I guess wwmayer fixed it: https://github.com/FreeCAD/FreeCAD/commit/c9923ab15
Could you bring this fix to your linkstage3 branch ?

**Comment by luzpaz** [comment]
@rgbertoni can you report back if this is still an issue?
