### ISSUE TITLE
[UI] Pad Parameters UI change

### ISSUE THREAD

**Issue by StudioPetrikas** [realthunder/FreeCAD#650]
Hello,

There seems to be changes in the Pad pad parameters task, and it does not play well with many themes. 

![sc-2022-11-30 20_41_12 tiff](https://user-images.githubusercontent.com/70055734/204895546-3036d6f0-1c9b-459e-9c6e-9b54f0339503.jpg)

If the buttons are have padding around text, the middle column becomes really narrow, preventing from reading the list of elements. 

![sc-2022-11-30 20_57_07 tiff](https://user-images.githubusercontent.com/70055734/204895906-15d41706-75f6-4a13-99f0-a0ab5a22c615.jpg)

I would propose to add these buttons below the selection window, with full, proper text, something like this:

![example](https://user-images.githubusercontent.com/70055734/204895651-3b3a250d-f3b1-4e5f-ab1c-06be9bce258b.jpg)

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1128.26244 +5318 (Git)
Build type: Release
Branch: LinkDaily
Hash: d45d221edcc7a757eb4e4eb638da0db5ed2759aa
Python version: 3.10.8
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United Kingdom (en_GB)

**Comment by realthunder** [comment]
Can send me your stylesheet? Those preinstalled stylesheet seem all work fine. The list view is supposed to be shown in single row mimicking a edit box. The reason being that I expect most sketch based feature will still use just one sketch element.

![image](https://user-images.githubusercontent.com/1207888/205310014-05caed0f-8f23-4406-b2df-7529fc63bc17.png)

**Comment by StudioPetrikas** [comment]
The top screenshot is the default stylesheet, clean install. 

![sc-2022-12-02 15_14_58 tiff](https://user-images.githubusercontent.com/70055734/205312591-0fea8a65-c61b-4e11-b42a-5f804ff4556f.jpg)

This looks like it might be a windows-only problem.

**Comment by realthunder** [comment]
I see, it only happens when the edit panel can be shown in its full height.
