### ISSUE TITLE
settings->display->shadow: ground settings

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD#653]
When I try to use the ground settings I get an error about copying when I change the view to Shadow (shortcut V 9)
The error
![ls3_3](https://user-images.githubusercontent.com/1257901/205434980-63595ba0-4d96-4359-87f6-80cf5d78cb38.png)

The bump and normal files:
![ls3_1](https://user-images.githubusercontent.com/1257901/205434972-7e7670c1-c88a-4b43-84f4-17e4d8cd305e.png)

The settings dialog
![ls3_2](https://user-images.githubusercontent.com/1257901/205434977-468694b0-b925-4620-9860-efc20de27b6c.png)

The version I am using right now
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1112.26244 +5306 (Git)
Build type: Release
Branch: LinkDaily
Hash: c64e4a49244a1c0ce9fd6455d18aa919d0db9c80
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: Dutch/Netherlands (nl_NL)

**Comment by snelweg** [comment]
Switched to the 28-11 release, same problem.

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1128.26244 +5318 (Git)
Build type: Release
Branch: LinkDaily
Hash: d45d221edcc7a757eb4e4eb638da0db5ed2759aa
Python version: 3.10.8
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: Dutch/Netherlands (nl_NL)

**Comment by realthunder** [comment]
Can you please try replace `/` with `\`.

**Comment by snelweg** [comment]
There is some magic going on.... It won't let me change the '\'
This happens with the native file dialog setting on or off.
 
![FreeCADLink_SEXGXUa6zX](https://user-images.githubusercontent.com/1257901/205605369-91b4db79-6481-4e16-8023-fe90b48d8d0c.gif)

**Comment by da-h** [comment]
**Possibly related**:
With the linux-AppImage, adding any picture on the system results in trying to copy it to the root-directory and fails with the following error:
```
 01:19:11  <Exception> Cannot copy file from /home/da-h/.FreeCAD/Gui/Stylesheets/groundtexture1.png to /groundtexture1.png
```

I could work around this by copying the file myself to the asked destination `/groundtexture1.png`, however. Changing the file then to another picture in the root directory yields again a similar error as above.

**Note**: Same applies for the `Ground Bump Map`-File Selector.

Best,
*da-h*
