### ISSUE TITLE
Freecad-gears add-on parameters have limits.

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#656]
Install freecad-gears add-on via Addon Manager. Create any gear, View parameters

![image](https://user-images.githubusercontent.com/8691781/205875600-28ab201f-8f02-4047-8514-0793ae3f92b0.png)

can't be set lower than these.

Base FreeCad allows set any value, and defaults are also different, though add-on installed in the same folder `AppData\Roaming\FreeCAD\\Mod\freecad.gears`

**Comment by realthunder** [comment]
The limit setting is exposed through `Preference -> Part design -> Shape view -> Tessellation`. Change those two `lower bound` settings. The lower bound is added because a value that is too small may cause freezing when opening a document. Not sure if later OCC version still has this problem.

**Comment by vovodroid** [comment]
Thanks, closing issue!
