### ISSUE TITLE
TopoNaming problem with subshape binders ?

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#657]
The problem occurs with the file: [spireFilter.zip](https://github.com/realthunder/FreeCAD/files/10173695/spireFilter.zip)
![Screenshot from 2022-12-07 08-22-35](https://user-images.githubusercontent.com/12879321/206116503-76036a63-7f36-4e0e-9b3f-58ff97af0fc6.png)

After changing "cap_thick" (you may set cap_thick=1.5) in "Parameters" Spreadsheet, the last 4 subshape binders inside body "BC_CAPS" loose the related faces. It is a strange because this parametric change doesn't affect the topology of the CAD structure.

**Comment by realthunder** [comment]
There is a bug in recent change of the face maker causing unstable output face index. You can fix the problem by doing a full recompute by marking the document for recompute, which effectively regenerate all topo naming.
