### ISSUE TITLE
Several Additive pipe issues. One causes Invalid Spine error. The other gives sections must be all open/closed error.

### ISSUE THREAD

**Issue by julia-m-stephenson** [realthunder/FreeCAD#677]
I can't find anything that matches this my google-fu is weak today. This works on vanilla 0.20.1.

I've selected a sketch and a path (Rotation Seam) to make an additive pipe.

![image](https://user-images.githubusercontent.com/52968628/211787478-f30e0024-1c0a-4e03-a833-2e4b524ac92e.png)

When Additive pipe is selected I get an Invalid spine error and the Rotation Seam (edge2) is de-selected. 
![image](https://user-images.githubusercontent.com/52968628/211787974-2c273736-7029-413a-8e53-e50471bcbd8c.png)

If I then make the rotated object visible and add the same sweep path. It works.

![image](https://user-images.githubusercontent.com/52968628/211788558-8645b7fb-65c0-4b41-aece-01a91aa684f6.png)

![image](https://user-images.githubusercontent.com/52968628/211788628-d6f2d713-3cd8-4d2e-8918-6521555ebc85.png)

(Ignore the timestamps on the second two pics Spine errors only happen on the initial Additive pipe.

I have attached the test file at the point just before the additive pipe. Excuse the weird object its an example of the Mango-Jelly_Solutions YouTube course!

My version details
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1128.26244 +5318 (Git)
Build type: Release
Branch: LinkDaily
Hash: d45d221edcc7a757eb4e4eb638da0db5ed2759aa
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United Kingdom (en_GB)

**Comment by julia-m-stephenson** [comment]
[cooker_knob_link_stage.zip](https://github.com/realthunder/FreeCAD/files/10391579/cooker_knob_link_stage.zip)

**Comment by julia-m-stephenson** [comment]
After some more playing you get the same error if just the sketch is selected and additional pipe is clicked.

**Comment by julia-m-stephenson** [comment]
Is there something broken on Additive Pipe? I can't get multi-section pipe to work either. I keep getting sections must be all closed or all open on a two section pipe. The exact same file works fine on vanilla 0.20.1 so I am sure the two sketches are closed with the same number of edges.

![image](https://user-images.githubusercontent.com/52968628/211803347-4cb4c0e1-5deb-43a8-a632-9fd96af50600.png)

On 0.20.1
![image](https://user-images.githubusercontent.com/52968628/211803574-0b092a6d-dd04-493e-882b-f7b7a9dfa75b.png)

Here's the file 

[cooker_knob_vanilla_link_stage.zip](https://github.com/realthunder/FreeCAD/files/10392149/cooker_knob_vanilla_link_stage.zip)

I notice there are a few other open issues mentioning pipe. 
[https://github.com/realthunder/FreeCAD/issues/638](url)
[https://github.com/realthunder/FreeCAD/issues/593](url)

Hopefully this file helps you track this issue down as its a fairly simple model.

Best Regards Julia

**Comment by realthunder** [comment]
There is an invalid multi-section feature. You probably added it by accident. You know when you first created the pipe, the first selection is considered as the base profile, the second is considered the sweep path, and the third and beyond are all considered as additional sections. I guess you were adding third section thinking it would belong to the sweep path. There is indeed some ambiguity here. Should be improved in the future.

Once removed it, the pipe feature can be made, but still with problem. Geometry checker will tell it is an invalid shape. You'll need to change `Corner Transition` to `Transformed` to make it work properly.

![image](https://user-images.githubusercontent.com/1207888/212206277-22c0ccef-b224-4841-a1a5-de6a4b2826c8.png)

**Comment by julia-m-stephenson** [comment]
Thankyou so much for taking the time to comment. Yes my mistake on adding the Edge4 in the section list. DOH!

I removed that and it worked 
![image](https://user-images.githubusercontent.com/52968628/212278536-dd677a65-cb7a-43d2-a6db-66b711e10e44.png)

It seemed corner transition was okay I didn't need to select Transformed.

The UI could be improved by having the sweep path list and the section list look the same (like the section list I think). Error handling could be improved by detecting the same object in both lists but thats probably asking a bit much!

However my first comment [https://github.com/realthunder/FreeCAD/issues/677#issue-1528833810](url) about the spine error still holds true. In vanilla FreeCAD you can select 1 Section and 1 Path and then hit the Additive pipe and it works fine. With Linkstage you still get the spine error.

Thanks again :-)

**Comment by realthunder** [comment]
The problem in OP is fixed by the above commit.

Regarding the corner transition, you can use `Check geometry` to see that it's an invalid shape. I've added new feature to notify `invalid shape` in tree view.

https://user-images.githubusercontent.com/1207888/212343043-5f38b64b-e2d6-417e-b6ce-9e31b3df685e.mp4
