### ISSUE TITLE
Missing version

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD#679]
FreeCAD-asm3-Daily-Win64-Py3-Qt5-2022.11.28

**Comment by hamza00789** [comment]
Can anyone explain now why this version is missing.

**Comment by hamza00789** [comment]
Can anyone contact I want to know about it..........................

**Comment by hamza00789** [comment]
Can anyone contact me?

**Comment by realthunder** [comment]
Please try the new release. You can choose the `LibPack` release.
