### ISSUE TITLE
Part rendering with many extra lines issue

### ISSUE THREAD

**Issue by daproph** [realthunder/FreeCAD#682]
Hello,

After I create a solid part and return to part design, the part will render with lines that are not part of it. The more features I add to it, the more lines I get. 
![RenderIssue1](https://user-images.githubusercontent.com/57709978/212554880-33482ad3-5422-4c41-896a-ed91419fbbfb.png)
They disappear when I highlight a face but return the moment I move or rotate the part. (Hovering over the navigation cube will also cause the lines to come back.) These lines also appear when I select a face and go into sketcher. 
![RenderingIssue2](https://user-images.githubusercontent.com/57709978/212554883-a28b2ee1-e3c5-4c8b-9a16-a6f3be181ebe.png)
I was thinking that it may be my system, however I don't have this issue when I use 043022 Stable. All the versions after that do produce these lines though.

I am at a loss on how to resolve this so any help would much appreciated.
System Specs:
OS: Windows 10
CPU: Athlon X4 880K
Graphics: Radeon RX 580

 Thank you

**Comment by bambukouk** [comment]
Might help if you share the file?

**Comment by realthunder** [comment]
Are you using the Conda or LibPack build? Can you please also try activate `Tools -> Preset configurations -> Display settings`?

**Comment by daproph** [comment]
> Are you using the Conda or LibPack build? Can you please also try activate `Tools -> Preset configurations -> Display settings`?

Using the LibPack build. Your activation suggestion worked. The parts no longer render with all the extra lines drawn. 
Thanks for your help AND thank you for all the hard work you put into fixing FreeCAD and making it something amazing Realthunder!

**Comment by iamtrendramas** [comment]
this also helped me, thanks again realthunder, much appreciate your work on this.
