### ISSUE TITLE
2023.01.14 crashes on macOS

### ISSUE THREAD

**Issue by michaelrommel** [realthunder/FreeCAD#683]
Hi,

the new version does not start on macOS. The terminal shows:

```
 '/Applications/FreeCAD.app/Contents/MacOS/RunFreeCAD'
dyld[4154]: missing symbol called
/Applications/FreeCAD.app/Contents/MacOS/FreeCADLink: line 27:  4154 Abort trap: 6           "$PREFIX/bin/$name" "$@"
❯ '/Applications/FreeCAD.app/Contents/MacOS/FreeCADLink'
dyld[4162]: missing symbol called
/Applications/FreeCAD.app/Contents/MacOS/FreeCADLink: line 27:  4162 Abort trap: 6           "$PREFIX/bin/$name" "$@"
```

The previous version on this same machine runs fine.
HWInfo:
Mac Studio
64 GB
macOS: 13.1 (22C65)

  Michael.

**Comment by andyylin** [comment]
Same for me, also not loading. 
macOS 13.1 (22C65)

**Comment by riparz** [comment]
Same for me
<img width="537" alt="image" src="https://user-images.githubusercontent.com/8463064/212736928-95319884-5a09-4fa0-8e73-282c46cb4261.png">


workaround: use BigSur version, seems to work fine.

**Comment by dimitris-banked** [comment]
Same for M1 Max running Ventura 13.1

**Comment by Zcool85** [comment]
Same for me
<img width="544" alt="Capture d’écran 2023-01-28 à 22 06 58" src="https://user-images.githubusercontent.com/12772987/215291130-30445e90-1e15-4053-98b6-6b4de47a3d4c.png">

**Comment by andyylin** [comment]
Fixed in latest release, this can now be closed.

**Comment by michaelrommel** [comment]
I can confirm, that it now works for me, closing this issue - thanks a lot!!
