### ISSUE TITLE
FEM_PostFilterDataAtPoint access violation

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#684]
Clicking on "Select point" causes an error:

![image](https://user-images.githubusercontent.com/8691781/212647204-4d51ea02-c201-49bb-938c-c6afcb196219.png)

It happens in any project, sample is attached.
[PointBug.zip](https://github.com/realthunder/FreeCAD/files/10424484/PointBug.zip)

**Comment by julia-m-stephenson** [comment]
Looks like there was a similar bug in Vanilla 0.19 according to this issue or is it a different dialog?
https://github.com/FreeCAD/FreeCAD/issues/7008

**Comment by vovodroid** [comment]
> or is it a different dialog?

I guess different. Bug you mentioned about wrong value, and my one about access violation.

**Comment by julia-m-stephenson** [comment]
> > or is it a different dialog?
> 
> I guess different. Bug you mentioned about wrong value, and my one about access violation.

The second bullet point in the Issue Description says it causes an access violation in FreeCAD 0.19 

Maybe that fix didn't make it to LinkStage?

**Comment by vovodroid** [comment]
> it causes an access violation in FreeCAD 0.19

It already works in 0.20

**Comment by julia-m-stephenson** [comment]
> > it causes an access violation in FreeCAD 0.19
> 
> It already works in 0.20

Yes but the fix may not have made it into Linkstage yet.
It might be this issue in Vanilla Freecad 
https://github.com/FreeCAD/FreeCAD/issues/6673

I will check to see if this fix is in Linkstage
https://github.com/FreeCAD/FreeCAD/commit/e9c088c0aef2

![image](https://user-images.githubusercontent.com/52968628/212670167-ee12f0d4-e520-46cc-85c3-d7c115407896.png)

And indeed it isn't so I think that's the problem - an upstream fix didn't make it into Linkstage yet. 
Hopefully @realthunder will see this and pull in this fix and the one for 7008

**Comment by vovodroid** [comment]
> the fix may not have made it into Linkstage yet.

I guess current realthunder version is 0.17 based.
