### ISSUE TITLE
Empty start page on linux appimage

### ISSUE THREAD

**Issue by oficinerobotica** [realthunder/FreeCAD#687]
The latest appimage release starts with an empty StartPage. This doesn't happen with the previous release on the same pc.

![empty_start_page](https://user-images.githubusercontent.com/26909793/212869727-0169678b-6bc1-472d-b75f-af4fb01ab801.jpeg)

OS: KDE neon 5.26 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 2023.114.26244 +5346 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 734bfcf15661aea45b019c0588e70e33c33ee73c
Python version: 3.10.8
Qt version: 5.15.6
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United States (en_US)

**Comment by mwlandolsi** [comment]
Same thing on other Ubuntu 22.04 

mine is 
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 2023.114.26244 +5346 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 734bfcf15661aea45b019c0588e70e33c33ee73c
Python version: 3.10.8
Qt version: 5.15.6
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United Kingdom (en_GB)

**Comment by dzervas** [comment]
I have this problem in both Wayland and X11.

```
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 2023.114.26244 +5346 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 734bfcf15661aea45b019c0588e70e33c33ee73c
Python version: 3.10.8
Qt version: 5.15.6
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United States (en_US)
```

**Comment by toastedcrumpets** [comment]
Confirmed on Arch with the snapimage

**Comment by realthunder** [comment]
Can you please try [this](https://drive.google.com/file/d/14SSynSLbqomZteZ4FDFqH6bXmr46h4cN/view?usp=share_link).

**Comment by dzervas** [comment]
> Can you please try [this](https://drive.google.com/file/d/14SSynSLbqomZteZ4FDFqH6bXmr46h4cN/view?usp=share_link).

Fixed for me!

**Comment by oficinerobotica** [comment]
Works for me too .... should we close this report?

**Comment by dzervas** [comment]
Better make a commit with the target issues that rolls the dependency back

**Comment by mwlandolsi** [comment]
looks good, Thank you

**Comment by oficinerobotica** [comment]
I see that the problem seems to be solved with the latest package provided by @realthunder  so I'm closing this report.
Thank you RT
