### ISSUE TITLE
PolarPatern : Occurences reset to 1 on editing

### ISSUE THREAD

**Issue by mgth** [realthunder/FreeCAD#697]
When editing an existing pollarpatern, occurrences value falls back to 1, loosing previous value.

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2023.114.26244 +5346 (Git)
Build type: Release
Branch: LinkDaily
Hash: 734bfcf15661aea45b019c0588e70e33c33ee73c
Python version: 3.10.8
Qt version: 5.15.6
Coin version: 4.0.1
OCC version: 7.6.3
Locale: French/France (fr_FR)

**Comment by discip** [comment]
I second that!

**Comment by discip** [comment]
# @realthunder
# Thank you! 👍🏻

**Comment by mgth** [comment]
👍🏻
