### ISSUE TITLE
External geometry Issues

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD#698]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2023.114.26244 +5346 (Git)
Build type: Release
Branch: LinkDaily
Hash: 734bfcf15661aea45b019c0588e70e33c33ee73c
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United States (en_US)

add External geometry - add/toggle intersection geometry Both are not working properly.

**Comment by hamza00789** [comment]
![1](https://user-images.githubusercontent.com/92737149/214666933-3c4e9db2-f349-4d95-afed-41379ab86a15.jpg)   

The result should have been something like this.  

![2](https://user-images.githubusercontent.com/92737149/214667040-54979dba-ae96-428d-a1cf-7cd310ad832f.jpg) 

[file.zip](https://github.com/realthunder/FreeCAD/files/10502844/file.zip)

**Comment by hamza00789** [comment]
![3](https://user-images.githubusercontent.com/92737149/214668376-11fd7a1d-95f5-4e9d-a2ca-807fb39f971f.jpg)
![4](https://user-images.githubusercontent.com/92737149/214668397-777fe198-6e06-47ab-a74f-099a786859c7.jpg) 

This part is coming extra which shouldn't come. 

![11](https://user-images.githubusercontent.com/92737149/214671840-381dba04-462b-4588-b24b-2aeaf0806e90.jpg)

**Comment by hamza00789** [comment]
![6](https://user-images.githubusercontent.com/92737149/214670145-ead94389-9aa7-4119-8c0f-60fb7c2bdb94.jpg)  

This part is coming extra which shouldn't come. 

![8](https://user-images.githubusercontent.com/92737149/214670177-17802bc5-474c-4f8e-8e01-77ede1c7cc39.jpg)          

The result should have been something like this. 

![9](https://user-images.githubusercontent.com/92737149/214670263-ea428a71-0f28-449d-9b9a-2681a8fddc6c.jpg)
 
[File 2.zip](https://github.com/realthunder/FreeCAD/files/10502951/File.2.zip)

**Comment by hamza00789** [comment]
You may fix these issues in the next release of

**Comment by hamza00789** [comment]
Even basic work in Freecad is impossible if these issues are not resolved.

**Comment by hamza00789** [comment]
Can you give me some guidance on these issues?

**Comment by hamza00789** [comment]
Thanks for solving the problem.  
This problem causes difficulty in working. And only you know when the new release will come.  
Can this issue be fixed in the same release as the method you described in this issue?#693

**Comment by hamza00789** [comment]
Can you guide me?

**Comment by hamza00789** [comment]
Can you guide me.....................

**Comment by hamza00789** [comment]
please inform me.

**Comment by hamza00789** [comment]
If you can't do that, you should at least respond.

**Comment by wohltat** [comment]
@hamza00789 
Please stop spamming and let people have a weekend.

**Comment by realthunder** [comment]
Yes, new builds are ready. I'll release it tomorrow. But, if you want some fix really bad, maybe try follow the build instruction and compile it on your own. You can follow the official build instruction. Just substitute the git repo.

**Comment by discip** [comment]
@hamza00789
> If you can't do that, you should at least respond.

You seem very ambitious, but your way of communicating is unacceptable to say the least.

Although the developer is not obligated to respond, and your attitude is not the first time like this, he does so anyway!

Try to be more patient and respect other people's private lives as they are human too and at some point they need rest and distance.

kind regards

**Comment by discip** [comment]
# @realthunder
# You are an honorable man and your behavior is exemplary in the highest degree! 👍🏻

**Comment by hamza00789** [comment]
If I have offended anyone because of my words, I apologize. But in my opinion, I did not say anything wrong. My native language is not English. You may find my behavior inappropriate due to the language change.
