### ISSUE TITLE
Missing TreeView from View menu

### ISSUE THREAD

**Issue by szimszon** [realthunder/FreeCAD#701]
Hi,

I wonder if you could help me.

FreeCAD version: https://github.com/realthunder/FreeCAD/releases/tag/2023.01.13-edge, Appimage 

After I removed the .FreeCAD folder from my home. I wanted to set up the UI to bring ComboView to the right and only the TreeView should be on left side. However the TreeView possibility is missing from the View menu.

![image](https://user-images.githubusercontent.com/745542/215753649-4c7858a9-778a-4acd-8859-cc59e92afdef.png)

Thank you!

**Comment by realthunder** [comment]
You can play around with the options below. Or, try either overlay light or dark theme presets in `Tools -> Preset configurations`.

![image](https://user-images.githubusercontent.com/1207888/215754676-d38bdd92-b8ec-4b27-8c7e-d65d3d3aa20c.png)

**Comment by szimszon** [comment]
My faullt. Sorry. It is there. Thank you!
