### ISSUE TITLE
Characters in Draft ShapeString

### ISSUE THREAD

**Issue by HappyUse** [realthunder/FreeCAD#704]
Hello
When I set some text in the string tool of the draft workshop, Freecad add a square after each characters whatever the font file selected.

![image](https://user-images.githubusercontent.com/124242266/216261682-7256ca0d-03a2-4614-abfe-a93efdd4037c.png)

**Comment by julia-m-stephenson** [comment]
This was fixed in December are you using the latest build?

[https://github.com/realthunder/FreeCAD/issues/628](url)

**Comment by HappyUse** [comment]
Thanks a lot. I update my version
