### ISSUE TITLE
Crash on PartDesign after canceling a polar pattern

### ISSUE THREAD

**Issue by YgorSouza** [realthunder/FreeCAD#71]
I created the attached file on FreeCAD 0.18.4 and then modified it with FreeCAD-asm3-Daily-Conda-Py3-Qt5-20201129-glibc2.12-x86_64.AppImage as a simple test.

After playing with the fillet and fit tolerance a few times, I clicked on polar pattern and then canceled it, and that caused a segmentation fault. It could not make it happen again. The output of the application before and during the crash is attached. 

OS: Ubuntu 20.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.11.29.23076 +2859 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: a491be7f04516e65647d77ceb2547fbd0adac1df
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

[pocket_backwards_compatibility_test_asm3.zip](https://github.com/realthunder/FreeCAD/files/5612921/pocket_backwards_compatibility_test_asm3.zip)

[asm3_crash_output_20201129.txt](https://github.com/realthunder/FreeCAD/files/5612922/asm3_crash_output_20201129.txt)

**Comment by luzpaz** [comment]
@YgorSouza can you retest?
