### ISSUE TITLE
Difference between 'Win Conda' and 'Win LibPack' releases?

### ISSUE THREAD

**Issue by D3SOL4TE** [realthunder/FreeCAD#713]
Sorry for my naivety but what's the difference between the two releases in the image below?
![Screenshot 2023-02-09 074836](https://user-images.githubusercontent.com/57688525/217751213-2388c0ee-6072-482b-a0e0-313e30513c9c.png)

**Comment by realthunder** [comment]
Major difference is the Python version. There are also minor version difference in other libraries used.

**Comment by D3SOL4TE** [comment]
Thanks.
