### ISSUE TITLE
Sketch line colors not updated according to constraint status

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#743]
In example the following image shows a full constrained sketch. 
The lines should be green instead of white.

![fullConstrainedSketch](https://user-images.githubusercontent.com/12879321/223108856-fa62a206-4a84-4eb0-b6cf-5a9c6ecea9e4.png)

**Comment by realthunder** [comment]
Just uncheck the `Show original color` option.

**Comment by wsteffe** [comment]
thanks, it works.
