### ISSUE TITLE
Sketches - to set and resize patterns

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#78]
The most terrible situation is when you create a size and the digits of this size get on some line. After that, it's very, very difficult to get to the line with the mouse and move it.

This is a problem common to all assemblies.

It would be right that the lines of diameter sizes should never be created matching the axes. It would be right not to overlay values on lines.
![Снимок экрана от 2020-12-05 18-54-54](https://user-images.githubusercontent.com/18741088/101247675-e4ff7380-372b-11eb-98d4-6d8fd402f0f0.png)

**Comment by realthunder** [comment]
Why not just drag the diameter/length constraint label out of the way.

**Comment by tiket18** [comment]
To drag it, you need to be able to select it, and to do this, you need to teach the program to select the size mark, and not the line or axis located there. This is the problem.

**Comment by tiket18** [comment]
When the figure lies on top of the line, it is useless to zoom in and poke with the mouse. The axis or line is selected.

**Comment by realthunder** [comment]
You can't select the line of a constraint, but you can select the label, the one that's showing the length or diameter.

![sketch-move](https://user-images.githubusercontent.com/1207888/101326714-a4793480-38a8-11eb-9487-b7e582760724.gif)

**Comment by realthunder** [comment]
Maybe you have set the pick radius too big.

![Screenshot from 2020-12-07 16-25-55](https://user-images.githubusercontent.com/1207888/101327018-0d60ac80-38a9-11eb-9d0a-28e348b54ded.png)

**Comment by tiket18** [comment]
я знаю, что выделять надо не линию размера, а цифры. Но если при создании ограничения цифра ложится поверх оси это сделать мягко говоря очень не просто. В этой связи и нужно научить программу не располагать цифры поверх линий.
I know that you need to highlight not the size line, but the numbers. But if, when creating a constraint, the figure lies on top of the axis, this is very difficult to do, to put it mildly. In this regard, it is necessary to teach the program not to place numbers over the lines.

**Comment by tiket18** [comment]
Yes, thank you, it helped - not so much the capture radius as the font size. But this is a bad way - with a rich sketch, a large font is very difficult.
![Снимок экрана от 2020-12-07 11-35-32](https://user-images.githubusercontent.com/18741088/101327994-813a8f00-3880-11eb-8216-c71951144633.png)
![Снимок экрана от 2020-12-07 11-32-10](https://user-images.githubusercontent.com/18741088/101328004-826bbc00-3880-11eb-9ce0-e01cccc3fb59.png)

**Comment by tiket18** [comment]
No, not hitting the mark and not resizing. This has to be fixed - it's not nice to spend so much time and effort on catching the size mark.
[size.FCStd.zip](https://github.com/realthunder/FreeCAD/files/5696310/size.FCStd.zip)
![Снимок экрана от 2020-12-15 16-49-59](https://user-images.githubusercontent.com/18741088/102223504-dcf6bf00-3ef5-11eb-904b-197ee0ff36e1.png)
![Снимок экрана от 2020-12-15 16-49-54](https://user-images.githubusercontent.com/18741088/102223510-de27ec00-3ef5-11eb-9fcb-5ad920d2e9a6.png)
![Снимок экрана от 2020-12-15 16-49-04](https://user-images.githubusercontent.com/18741088/102223514-dec08280-3ef5-11eb-8eca-88730869b7b2.png)

**Comment by realthunder** [comment]
Can you please capture a screencast video or gif to explaining your problem? I still don't quite get your problem yet.

**Comment by Shkolik** [comment]
Since radius/diameter constraints now creates with some angle to the axis by default there in no this issue anymore.
