### ISSUE TITLE
Appimage does not respect the current working directory

### ISSUE THREAD

**Issue by davidosterberg** [realthunder/FreeCAD#79]
When starting FreeCAD in a specific working directory (for example from the command line). FreeCAD will set the working directory to the /tmp/... path. Expected result is that FreeCAD starts in the current working directory.

I have tested and this works fine in FreeCAD 0.19 standard. 

![Working_dir_FreeCAD_LinkStage3](https://user-images.githubusercontent.com/1278189/102006676-2216c780-3d23-11eb-86dd-2cd6fb37f021.gif)

OS: Ubuntu 20.10 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.12.08.23076 +2912 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 1eba27283118bae43f5264d38caf7451b848f49a
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
I have just updated the AppImage release to 12.14 for the fix. I didn't mention it in the change log as this is just a minor fix of the startup script for AppImage only.
