### ISSUE TITLE
A new spreadsheet behaviour?

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD#8]
Hello
LinkDev branch, commit 9f80debbc0fdaec4d100538ed781eb3e37df71b3

I can no longer just type text in the cell. For some reason, the “=” sign is added automagically, which leads to an error.
Maybe I should somehow enter the text differently?
![spreadsheet](https://user-images.githubusercontent.com/6075465/47254085-3ee74580-d4a0-11e8-825a-9344d8794a12.gif)

**Comment by ceremcem** [comment]
I'm not using LinkDev branch, but would you try `'This is text`?

**Comment by realthunder** [comment]
> I'm not using LinkDev branch, but would you try `'This is text`?

Yes, a starting `'` can force plain text. 

Please be warned. I am doing a major refactor of expression inside LinkDev branch. You may encounter many strange behavior with spreadsheet before it become matured. The file you saved in LinkDev may not be able to open once the branch is merged.

**Comment by yrabbit** [comment]
Thanks, ```'``` does the trick :)

**Comment by ceremcem** [comment]
> Please be warned. I am doing a major refactor of expression inside LinkDev branch.

We're all holding tight :D
