### ISSUE TITLE
Loading FEM workbench error in latest build 20230507

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#805]
When running https://github.com/realthunder/FreeCAD/releases/download/Tip/FreeCAD-Link-Tip-Win-x86_64-py3.10-20230507.7z:

![image](https://user-images.githubusercontent.com/8691781/236683044-c25195a0-4bf8-4ce3-87d1-03585a9d3ed2.png)

**Comment by realthunder** [comment]
This should be fixed in the 0516 Tip release
