### ISSUE TITLE
Not possible to fillet a PAD created from B-Spline

### ISSUE THREAD

**Issue by projectcad** [realthunder/FreeCAD#82]
Not possible to fillet a PAD (in Part Design WB ) created from B-Spline

**Comment by ceremcem** [comment]
Please provide reproduction steps and version info of FreeCAD you are using, so we may at least confirm the issue with the latest commit if you're not using the latest commit.

**Comment by projectcad** [comment]
Tried it in two ones..but same.. Not possible to fillet the PAD created from B - Spline.... (in Part Design WB, 
Body >Sketch >Closed 5-6 pointed B-Spline>PAD> Fillet) 

1-) Freecad 0.19 Linkstage3 branch version Git 25985

2-) Freecad Daily 0.19....2020/12/14 21:36
![IMG_20201224_155939](https://user-images.githubusercontent.com/68682837/103092489-6e59e580-4608-11eb-85b3-e47700bdea6a.jpg)

**Comment by projectcad** [comment]
By the way, "chamfer" is possible on this object mentioned above. @realthunder

**Comment by projectcad** [comment]
It is possible any more...thank you @realthunder 
![BsplinePadFillet](https://user-images.githubusercontent.com/68682837/111898917-116ca080-8a3a-11eb-92d4-c059961a173b.png)

https://github.com/realthunder/FreeCAD/commit/bdbff46007be5f7f53e229ac19ff5db7177fe948

CC : @ceremcem
