### ISSUE TITLE
parameter update failing

### ISSUE THREAD

**Issue by erwanyves** [realthunder/FreeCAD#820]
I use a nut from fasteners workbench. in my project, I want to change the size of this nut on different versions. In order to get it centered, I use in Z position placement the formula: " -.Shape.BoundBox.ZLength / 2 ". When I open the formula editor, the evaluated function is correct, but differs on that taken into account (e.g I have a M6 Nut centered, I change to M12 , the evaluated function is correct in the dialog box, but the parameter stays on the previous value. The only way I done is to change "fix shape" whatever the choosen value, changing "validate shape", or changing another placement parameter (x, y). It seems that if the nut is changed, there is no check if placement parameters have changed.
[nut02.zip](https://github.com/realthunder/FreeCAD/files/11497484/nut02.zip)

![screenshot](https://github.com/realthunder/FreeCAD/assets/4448464/0c59d464-8ce1-4366-8a94-91a0e1b2d07e)

**Comment by erwanyves** [comment]
[nut02.zip](https://github.com/realthunder/FreeCAD/files/11497471/nut02.zip)

**Comment by realthunder** [comment]
This is not really a bug. The expression engine works at a lower level. It does not have knowledge on how the feature computes its shape, which may or may not use the `Placement` as input. If it is used as input, then your expression will create a dependency loop, which may cause the shape to move to a difference place every time it is recomputed. If it is not used as input, then it will work, but you as the user must manually mark the property `Placement` as an `Output`. Right click the property in property view, and choose `Show all`, and then check the option `Output`.

**Comment by erwanyves** [comment]
Thank you Zheng for your reply. Even if I check the option output it do not works. I saw that the item NoRecompute is checked and its state can't be changed.

**Comment by erwanyves** [comment]
Sorry, it works. I just try on a new file. Thank you, I close this "issue"
