### ISSUE TITLE
render cache not work, slow FPS in Link Tip release

### ISSUE THREAD

**Issue by ftdt10** [realthunder/FreeCAD#821]
Set the Render Cache to Experimental, 
but frames per second is decreased by half in Link Tip release version.

---
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2023.516.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: b3832bb2e9026abbb57a2f726603fa97994bc930
Python 3.11.3, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * Assembly3 0.12.0
  * Curves 0.6.9
  * fasteners 0.4.56
  * kicadStepUpMod 10.19.1
  * kicadStepUpMod.backup1684338274.0809298 10.19.1 (Disabled)
  * POV-Ray-Rendering
  * QuickMeasure 2022.10.28
  * Render 2023.2.5
  * Render.backup1684338330.7047546 2023.2.4 (Disabled)
  * sheetmetal 0.2.63
  * TabBar
---

**Comment by realthunder** [comment]
I can't seem to reproduce the problem. Any particular file you are testing? Are there any frame rate difference in render cache `Experimental` and `Auto`.

**Comment by ftdt10** [comment]
The problem only happens on Windows.
It's normal on Ubuntu.

I renamed bin/opengl32sw.dll to bin/opengl32.dll
due to black screen problem.
https://forum.freecad.org/viewtopic.php?t=36087&start=40
But, I think it has no relation with the probelm.

**Comment by ftdt10** [comment]
In Task Manager, I have confirmed that GPU is not being used, only the CPU is being used.
FreeCAD weekly release has the same problem.

GPU is being used normally in the following release.
FreeCAD-asm3-Daily-Win-Conda-Py3.10-20230131-x86_64.7z
FreeCAD-asm3-Daily-Win64-LibPack-Py3.8-20230131.7z

**Comment by realthunder** [comment]
> I renamed bin/opengl32sw.dll to bin/opengl32.dll
> due to black screen problem.
> https://forum.freecad.org/viewtopic.php?t=36087&start=40
> But, I think it has no relation with the probelm.

The `sw` in `opengl32sw.dll` means software. You are forcing FreeCAD to use software only opengl, hence no GPU usage. What are the error message you have when using `opengl32.dll`?

**Comment by ftdt10** [comment]
![image](https://github.com/realthunder/FreeCAD/assets/119850346/64e103b5-7c93-47d9-9634-4b56c181ba78)
It's error message in the black screen problem.

**Comment by realthunder** [comment]
When do you have this message? When FreeCAD just start up? What graphics card do you have?

**Comment by ftdt10** [comment]
It's error message when FreeCAD just startup. I'm using Intel HD5500 iGPU. Driver is latest 11/4/2020, 20.19.15.5171.

**Comment by ftdt10** [comment]
I just tested in other PC with AMD 5600G iGPU or NVidia GTX1650 dGPU, 
but there is no black screen problem.
It seems it's problem for the older graphics card.
I hope it works for the HD5500 also.

**Comment by realthunder** [comment]
Can you please try download again. Same name, but rebuilt with older qt. Let me know if it works.

**Comment by ftdt10** [comment]
It works now. 
There is no black screen error. The FPS is at its maximum as before.
Thanks for the rebuild.
