### ISSUE TITLE
Mirror/Pattern Tools Can't Select Multiple Features 

### ISSUE THREAD

**Issue by Trakyan** [realthunder/FreeCAD#839]
So I noticed this issue in the mirror tool intitially, but it seems to occur with the other transform tools (linear pattern, etc.)
The tool "works" but only on the last feature before the transform. Ticking the box beside other features does nothing, and when you click OK in the combo view to close the transform, and open it again all the boxes are unticked. 

This issue seems to exist in the Tip release but not the 2023.01.31 version from what I can tell. 

If a mirror is created with multiple features in 23.01.31, it will open correctly in the tip release but I won't be able to change what features are used in the mirror.

I'm running EndavourOS which is based on Arch Linux.

Wondering if anyone else can replicate this issue, or if it's again something caused by having mainline and linkstage alongside each other.

Below is a screenshot of the issue.
![image](https://github.com/realthunder/FreeCAD/assets/37814637/fb027df3-e5a9-4bd4-b0ac-e002c055fd55)
![Screenshot_20230624_193541](https://github.com/realthunder/FreeCAD/assets/37814637/cc35f5d5-4642-4c7c-af8f-60a9e84ebad2)

**Comment by Trakyan** [comment]
Just tried it on a live USB with only the LS3 appimage, the issue is still there. It is also present in the 0.21 weekly build app image from the main branch (03/06/2023), but not the latest weekly build.

**Comment by Trakyan** [comment]
Further testing on a windows laptop has the issue present as well. Someone suggested I try selecting the features from the properties view, and that worked.
Below shows the original bug:
![Screenshot_20230629_194848](https://github.com/realthunder/FreeCAD/assets/37814637/fad57a4d-d0c5-4a38-953a-3d1e3f9709cd)
Then going through the properties panel allows me to actually select multiple (and also not just the most recent) features
![Screenshot_20230629_195527](https://github.com/realthunder/FreeCAD/assets/37814637/7a670765-c46b-4575-98b1-6d5977ca3c66)
 
Additionally, the bug seems to be present in mirror and linear pattern, but not in polar pattern.
I should maybe add this issue is not present in the "daily" release, only the "tip" release.

**Comment by oerkel47** [comment]
I can confirm this bug and the workaround using the properties panel. Also can confirm the multiple texts on top of each other in the mirror parameter screen.

**Comment by wohltat** [comment]
I can confirm the bug. 
Present in 2023-05-21 and not in 2023-01-31.

It looks like this:
![mirror-not-working-2023-5-21](https://github.com/realthunder/FreeCAD/assets/4751351/049a434d-5f17-4de1-9417-855532d85e21)

and should look like this:
![mirror-working-2022-11-12](https://github.com/realthunder/FreeCAD/assets/4751351/b1f31c11-8efd-4414-9c87-d08c54f81b07)

In my opinion a mayor bug since the workaround does not offer a preview and almost no user will find it.
Is it just my feeling or is there not much happening at the moment on that branch?
