### ISSUE TITLE
BoundingBox not showing

### ISSUE THREAD

**Issue by ghost** [realthunder/FreeCAD#856]
Hi
If I turn the Bounding Box option to true (Property) nothing changes. It should show the rectangle and the measurements.

Thanks for your help.
Markus

![image](https://github.com/realthunder/FreeCAD/assets/119668534/00f84af2-14eb-45a1-b5d0-d7068e48812d)
![image](https://github.com/realthunder/FreeCAD/assets/119668534/deaf3775-19b6-44a2-b722-7c8f037a9609)

I use:
[code]
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 2023.731.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: 311c0066f7d2e5599a76337706627b6c27f6dc2b
Python 3.11.4, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: German/Switzerland (de_CH)
Installed mods: 
  * boltsfc 2022.11.5
  * Curves 0.6.6
  * DynamicData 2.46.0
  * fasteners 0.4.25
  * Manipulator 1.4.9
  * ThreadProfile 1.85.0
[/code]

Testfile: [BoundingBox.zip](https://github.com/realthunder/FreeCAD/files/12225765/BoundingBox.zip)

**Comment by eblanshey** [comment]
Your model is showing a tiny bounding box, but not around the whole part for some reason:

![image](https://github.com/realthunder/FreeCAD/assets/3145217/bfb97ef0-ad50-4609-bbc0-4f2d649e9eb8)

The bounding box is working for my other parts, though. Maybe it has something to do with your fusion, or something else with the part.

It's working in stable 0.20.2, though. So maybe it's a bug with RT FreeCAD.

![image](https://github.com/realthunder/FreeCAD/assets/3145217/682565d8-9ec2-4d30-9e71-a953f34f37bd)

**Comment by ghost** [comment]
Thanks, I tried it in stable version 0.20.1 and it's working.

In RT FreeCAD the bounding box is not working even for simple sphere or boxes.

**Comment by ghost** [comment]
Thanks, with version 20230806 it ist working.
