### ISSUE TITLE
No default solver is added upon FEM Analysis creation

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#859]
In version 

[code]
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 2023.731.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: 311c0066f7d2e5599a76337706627b6c27f6dc2b
Python 3.11.4, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: English
[/code]

![image](https://github.com/realthunder/FreeCAD/assets/8691781/ec8be434-64ea-4ee8-b56a-c6d4d79e14a8)

**Comment by realthunder** [comment]
Maybe that's how upstream FEM works now. You'll need to manually click the 'Solver' icon button.

**Comment by vovodroid** [comment]
Indeed.
