### ISSUE TITLE
[UI] DockWindow transparency

### ISSUE THREAD

**Issue by obelisk79** [realthunder/FreeCAD#86]
I recently switched to Manjaro Linux from Windows and have been setting everything up using the latest daily (12/30) to get back to production like I'm used to.

However I seem unable to get truly transparent dockwindows. They have a translucent grey background instead. I hope I'm just missing a setting somewhere. I've taken a screenshot where you can see the translucency how I positioned the navi-cube.

https://imgur.com/YHut3up.png

If relevant I'm using the proprietary nvidia gpu drivers on an RTX 2060. I've tried with both the 455 and 460 beta series drivers.

**Comment by realthunder** [comment]
Select the 'Dark-overlay' as the `Overlay style sheet` in Preferences -> General.

**Comment by obelisk79** [comment]
Thanks for the quick response. I feel a bit silly now, but that worked great! Truly appreciate all the work you do on FreeCAD.
