### ISSUE TITLE
Assembly 3 Workbench not working

### ISSUE THREAD

**Issue by ghost** [realthunder/FreeCAD#860]
Hi
If I switch to the assembly 3 workbench the following message is displayed:
![image](https://github.com/realthunder/FreeCAD/assets/119668534/e84d5eac-3c64-4bb2-9d14-d2d00fccd1cb)

After pressing YES and waiting the following error message is shown:
![image](https://github.com/realthunder/FreeCAD/assets/119668534/8f7b2455-d618-450e-af01-dc81d8e36147)

14:53:31  During initialization the error ""'ManipulatorWB' already exists."" occurred in ...\FreeCAD\Mod\Manipulator.backup1690889244.466555\.\InitGui.py
14:53:31  Please look into the log file for further information

It seems that it isn't a solver installed:
![image](https://github.com/realthunder/FreeCAD/assets/119668534/01f7dc22-9767-4f46-93d7-6c0b212636a5)

I use the following version of FreeCAD:
[code]
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 2023.731.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: 311c0066f7d2e5599a76337706627b6c27f6dc2b
Python 3.11.4, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: German/Switzerland (de_CH)
Installed mods: 
  * boltsfc 2022.11.5
  * Curves 0.6.13
  * Curves.backup1690889256.6127493 0.6.13 (Disabled)
  * DynamicData
  * DynamicData.backup1690889267.1333668 2.46.0 (Disabled)
  * fasteners 0.4.59 (Disabled)
  * Manipulator 1.5.0
  * Manipulator.backup1690889244.466555 1.4.9
  * ThreadProfile 1.85.0
[/code]

Thanks for your help.
Markus

**Comment by eblanshey** [comment]
I had a similar issue with the latest link tip on Windows, except I was getting warnings like when installing:

```
WARNING: Skipping C:\Users\Mine\Programs\FreeCAD-Link-Tip-Win-x86_64-py3.11-20230730\bin\Lib\site-packages\vtk-9.2.5.egg-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Mine\Programs\FreeCAD-Link-Tip-Win-x86_64-py3.11-20230730\bin\Lib\site-packages\vtk-9.2.5.egg-info due to invalid metadata entry 'name'
```

My fix was to go to the installation's bin directory and reinstall the solver:

```
python.exe -m pip uninstall py_slvs
python.exe -m pip install py_slvs
```

Then when I opened FreeCAD and Assembly3 file it started working.

**Comment by ghost** [comment]
Perfect solution. Thank you :-)

**Comment by eblanshey** [comment]
@kotrans I just started actually working with an Assembly3 model, and none of the constraints are solving -- the parts can be moved in any direction, as if constraints don't work. Are you getting the same issue?

**Comment by ghost** [comment]
I had the same issue **before** I uninstalled and installed again the solver.

Bevore
![image](https://github.com/realthunder/FreeCAD/assets/119668534/8aeb622b-2367-461a-817c-b6ee82187a9c)

After
![image](https://github.com/realthunder/FreeCAD/assets/119668534/f9ad04f3-8981-45cb-9b49-1506ea317212)

And now it works perfectly. I checked it with the following two parts and I can turn the handle and move the parts and the stay together:

![image](https://github.com/realthunder/FreeCAD/assets/119668534/6db688fa-4f0d-489b-af78-f194c74ebd2d)

**Comment by eblanshey** [comment]
Thanks @kotrans. I didn't notice your comment, but ended up solving it as described in my [issue](https://github.com/realthunder/FreeCAD/issues/861).
