### ISSUE TITLE
FEM error: wrong ccx binary

### ISSUE THREAD

**Issue by Neubo** [realthunder/FreeCAD#862]
Hello,

when I double click on "SolverCcxTools,", I get an error message:

![image](https://github.com/realthunder/FreeCAD/assets/92023797/ae1fee93-3b1f-46c2-a67b-e887acdd7925)

and later, the message in console : 

`CalculiX can not be started. Missing or incorrect CalculiX binary: C:/_Data/Freecad/FreeCAD/bin/ccx.exe`

I've checked the parameters:

![image](https://github.com/realthunder/FreeCAD/assets/92023797/84f2c0b9-fa0e-47b8-a94e-f24485c6f378)

and the file does exist at the right place (same file as in the main Freecad branch)

May you need more information, don't hesitate to ask.

```
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 2023.806.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: 93dae74dba4a80dba52f9c5fe73fe5a874bae809
Python 3.11.4, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * DVPScaled.brep
  * Manipulator 1.5.0
  * parts_library
  * QuickMeasure 2022.10.28
```

**Comment by Neubo** [comment]
To complete my tests, I've changed the "CCX Binary Path" in CalculX preferences to point to the ccx.exe file located in the Freecad main branch's bin directory, and it works like that.

But two ccx.exe files (from bin directories) look pretty the same. Stange isn't it ? (At least, strange for me)

**Comment by Neubo** [comment]
another thought, I've copied the ccx.exe file from official Freecad to RT Freecad bin directory, and change settings in FEM preferrences. It doeasn't work.
I believe there somthing missing (dll, or other flags) in RT release ?

**Comment by Neubo** [comment]
[vovodroid](https://github.com/vovodroid), I just wonder if you don't have the same issue ?

**Comment by Miksu80** [comment]
I have same issues with 11.8.2023 and previous and also on linkstage 3. Also the dependencies are missing..

**Comment by Neubo** [comment]
Hello @Miksu80, if I'm right, realthunder referenced this issue, but has not yet release it in the last TIP.
But I've heard next TIP is about to come ;)
Maybe a new merge with the latest Freecad mainbranch version ? 

By the way, the workaround is easy (see above)

**Comment by Miksu80** [comment]
@Neubo Yes, the fix didnt make it to the latest tip release. I don't use FEM frequently but was sad to see it failing to start. Hopefully the merge with main branch will happen :)

**Comment by Neubo** [comment]
Hello !

It does not work much better with last TIP release (2023-10-18).


OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 2023.1018.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: ea554afc8427b011877bb340a0f6fd2bd942fe6f
Python 3.11.6, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * DVPScaled.brep
  * Manipulator 1.5.0
  * parts_library
  * QuickMeasure 2022.10.28
`

**Comment by Neubo** [comment]
Hello,

if this commit and the new release 17 hours ago should solve the "Wrong CCX lib" issue, it doesn't.
Or do I test it in the wrong way ?

In the FEM/CalculX, If I point directly to the ccx.exe in freecad/bin or if I check "search in known binay directories", it failed.
If I point to the ccx.exe file in freecad/bin of the official/main freecad branch, it works.

Don't hesitate if it's not clear of if you need more details.

**Comment by realthunder** [comment]
I have repackage the bundle. Please download again and try.

**Comment by Neubo** [comment]
Thanks, I confirm, it works now !
