### ISSUE TITLE
Last Tip version won't launch

### ISSUE THREAD

**Issue by Neubo** [realthunder/FreeCAD#866]
Hi,

when launching tip version 2023.08.10  with RunFreeCAD.bat under Windows 11 (using py3.8 or py3.11), I get this message:

![image](https://github.com/realthunder/FreeCAD/assets/92023797/ca2c1af8-de59-4733-8933-531f1b662546)

Launching FreeCAD-Link-Tip-Win-x86_64-py3.11-20230806 still works.

**Comment by Pendelf** [comment]
Confirm

**Comment by Thorn72** [comment]
Hello
Same problem but it can be easily corrected by copying the plugins directory from the previous version to the latest version
