### ISSUE TITLE
Unpack problem for the windows version

### ISSUE THREAD

**Issue by dingolino** [realthunder/FreeCAD#869]
Hi, since a couple of Versions I am getting a error during unpacking the windows version, that files are missing.

Please see attached pictures. I can skip it and umpacking continou, but it does not look "nice" getting a error meassage during unpacking.

![2023-08-12 09_59_35-(100%) Kopieren - Directory Opus](https://github.com/realthunder/FreeCAD/assets/18245441/64642ba3-caaa-4125-9a28-49ded17bd6c2)
![2023-08-12 10_00_06-(100%) Kopieren - Directory Opus](https://github.com/realthunder/FreeCAD/assets/18245441/380fe301-700b-4471-8b72-645ebf262c4a)
![2023-08-12 10_00_23-(100%) Kopieren - Directory Opus](https://github.com/realthunder/FreeCAD/assets/18245441/2e5d2442-30d5-48e4-b61a-926826e6ebcc)
![2023-08-12 10_00_38-(100%) Kopieren - Directory Opus](https://github.com/realthunder/FreeCAD/assets/18245441/cb3ab22a-ef43-498d-b6ef-b9c7ca399710)

**Comment by Thorn72** [comment]
hello,

I don't have this problem, I'm on windows 10 and I use the portable version of freecad.

**Comment by dingolino** [comment]
Hi,
was digging a little bit deeper. Please see attached screen shot.
I updated my 7zip from 22.01 to 23.01 (it was not "that old") and now the error meassage is gone.

Best regards,

![2023-08-18 09_23_54-100% Testing D__Daten2_install_   py3 11-20230811 7z](https://github.com/realthunder/FreeCAD/assets/18245441/72f3aa03-d32c-46f3-a7a9-32c46a93f5b8)
