### ISSUE TITLE
How to use TreeParams.py 

### ISSUE THREAD

**Issue by Kuzma30** [realthunder/FreeCAD#900]
I add new param to src/Gui/TreeParams.py  file. When I try run it (python3 TreeParams.py) it don't log anything. And produce no autogenerated code too.
What is correct way to use it? (ask as you author of this script)

**Comment by realthunder** [comment]
The usage is documented in each auto generated header file, i.e. `TreeParam.h`. Basically, you need to install pip package `cogapp`.  The code stub in a source file, e.g. `Gui/TreeParam.h`, looks something like,

```c++
/*[[[cog
import TreeParams
TreeParams.declare_begin()
]]]*/

//[[[end]]]
```
To auto generate the code, run the following command,

```shell
python3 -m cogapp -r Gui/TreeParams.h
```
It basically calls the python code in the comment block, and insert whatever it spits out (by invoking `cog.out()`) in place.

I might add cMake rules in the future to automate the above steps in build process.

**Comment by Kuzma30** [comment]
Thanks
