### ISSUE TITLE
Dcument recomputing failed

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#905]
Recomputing of FreeCAD document failed

[Direct-steel.zip](https://github.com/realthunder/FreeCAD/files/13310016/Direct-steel.zip)

FreeCADLink version: FreeCAD-Link-Tip-Win-x86_64-py3.11-20230811

**Comment by GinTonic99** [comment]
You might consider reading the error messsages, identify the erroneous sketches by looking for exclamation marks in the hierarchy and repairing the defect sketches

**Comment by vovodroid** [comment]
Sure I can. But it's supposed to be recomputed automatically.

**Comment by GinTonic99** [comment]
Without you having repaired the faulty sketches,  no recompute is possible; neither manually nor automatically.

**Comment by vovodroid** [comment]
But why do you consider they "faulty"? Upstream FreeCad open them, so I expect FC Link open and recompute them too.

**Comment by realthunder** [comment]
The above commit fixes the problem. You can try by either compile FreeCAD yourself, or wait till the next release.

There is still one recompute failure in `BaseSketch001` (i.e. `Sketch023`). If you double click the sketch to edit, it will complain of `Invalid sketch`, which may happen if you somehow saved your project while editing the sketch. The upstream FreeCAD reports the same thing if you try to edit the sketch, but the error does not show up if you recompute, which is arguably not a desired behavior.

**Comment by vovodroid** [comment]
> The above commit fixes the problem

Great!

> You can try by either compile FreeCAD yourself

Well, I tried it in the past, but without success.
