### ISSUE TITLE
Can't add Addons using Addonmanager 

### ISSUE THREAD

**Issue by ElPatoNoEsTu** [realthunder/FreeCAD#912]
Hi, 

Whenever I try to install an Addon i get an Error. OS is Windows 10. 

23:40:48  An error occurred updating macros from GitHub, trying clean checkout...:
Git returned a non-zero exit status: 128
Called with: C:/Temp/FreeCAD-Link-Tip-Win-x86_64-py3.11-20231102/bin\git.exe clone --recurse-submodules https://github.com/FreeCAD/FreeCAD-macros.git C:/Users/myname/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros

Returned stderr:
Cloning into 'C:/Users/myname/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros'...
warning: templates not found in C:/Temp/FreeCAD-Link-Tip-Win-x86_64-py3.11-20231102/share/git-core/templates
git: 'remote-https' is not a git command. See 'git --help'.

Please don't hesitate to come back to me in case of questions or in case that you need mor information. 

Many thanks in advance, 
Stefan

**Comment by farahats9** [comment]
I am having the same issue and error in 20240317. 

Could you please re-open?
