### ISSUE TITLE
Bug with Wireframe Rendering

### ISSUE THREAD

**Issue by samin50** [realthunder/FreeCAD#916]
@Hi,
I have encountered a weird bug, and I think it happened right after I uninstalled the official version of FreeCAD to free up space.
For some reason I get these random lines coming out of my geometry, and I believe it is a wireframe issue; if I change the draw style to wireframe only I see these lines, but I do not if I switch it to shaded.
![image](https://github.com/realthunder/FreeCAD/assets/94698788/58eabcbb-bcfc-4c21-ae8e-f303e7e0e1c6)
![image](https://github.com/realthunder/FreeCAD/assets/94698788/15ece8af-1009-4774-b17c-c0d6a93dd1bc)

I am not actually sure if the uninstall of the official version of FreeCAD caused this, but thats the only thing I could think of. I reinstalled it and downloaded the latest version of realthunder but no change.

EDIT: I should also add that this does not happen if I open the same file with the official version of FreeCAD.
This also happens to all files, any file I open renders with these weird wireframes, it is not local to my specific file.

EDIT2: realthunder's suggestion of Tools -> Preset Configurations -> Display settings fixed it??

**Comment by realthunder** [comment]
Could you please attach the file here? Also please post your setting file, `Tools -> Edit parameters -> Export`.

Please also try `Tools -> Preset Configurations -> Display settings` and see if it helps.

**Comment by samin50** [comment]
That seemed to work wow, can't believe it was that simple. I should just mention that it happened across all files too not just my local one. I would still attach my setting file but I attempted your fix first and I feel whatever was wrong with my display file has now been fixed by your suggestion
