### ISSUE TITLE
No Windows build in latest release

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
Latest
```

### Subproject(s) affected?

None

### Problem description

No Windows asset here: https://github.com/realthunder/FreeCAD/releases/tag/20231231stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jj-uk** [comment]
The windows builds are now there but 7-zip reports an error when extracting either .7z file.

![image](https://github.com/realthunder/FreeCAD/assets/10943625/4e2083d7-54f3-4eb1-bfee-3eb738b7a64e)

**Comment by vovodroid** [comment]
I opened and run it, try download again.

**Comment by vovodroid** [comment]
But I used WinRar, not 7zip.

**Comment by jj-uk** [comment]
7zip was out of date. Updated and now all ok.
