### ISSUE TITLE
Sketch problems with last LinkMerge

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.38946 (Git)
Build type: Unknown
Branch: LinkStable
Hash: 2eaff092937eeee5c382f9ddba0472c86c8b80d1
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.0
Locale: English/United States (en_US)
Installed mods: 
  * asm3 0.12.0
  * Assembly4 0.50.2
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

In the image below I added a small rectangle to thew first sketch and I trimmed a couple of edges of this rectangle. FC produced the following error:

> Sketch> SketchObject.cpp(11357): cannot find subname ;g86.edge55

After that it was not possible to move the remaining two edges of added rectangle, In this case FC produced following additional errors:

> 12:00:33  Unhandled unknown C++ exception in ViewProvider::eventCallback (Event type: SoLocation2Event, object type: SketcherGui::ViewProviderSketch)
> 12:05:54  App.getDocument('planimetria').getObject('Sketch').movePoint(55,0,App.Vector(-264.600341,-11.199707,0),1)
> 12:05:54  Drag curve: Not able to move point with the id and type: (55, 0)
> 
> 

[planimetria.zip](https://github.com/realthunder/FreeCAD/files/14075730/planimetria.zip)

 
![Screenshot](https://github.com/realthunder/FreeCAD/assets/12879321/e0c3fdd1-07ed-490e-8804-4641a539b474)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
> Sketch> SketchObject.cpp(11357): cannot find subname ;g86.edge55

This is a harmless error which I'll fix shortly. The problem probably happens when you drag the curve somehow lock up the sketcher solver. Is this problem reproducable? I can't seem to do that.

**Comment by wsteffe** [comment]
In the last year I encountered very often this kind of problem.  I think it started with in may 2023 after the last sync with upstream .
Actually this problem can be reproduced without trimming. You may also get this error by deleting the vertical length highlighted in the following picture:

![Screenshot from 2024-03-09 12-31-21](https://github.com/realthunder/FreeCAD/assets/12879321/d7b275f3-6f7d-4413-8c5f-07da46dffdb9)

and then trying to move the vertical position of the vertex highlighted in the next picture:

![Screenshot from 2024-03-09 12-34-11](https://github.com/realthunder/FreeCAD/assets/12879321/acdb16bc-69d7-4d94-9c6b-784f7ce9c104)

**Comment by realthunder** [comment]
Still can't reproduce the problem. Could you please post the file in the state just before dragging? And also please post your user configuration file.

**Comment by wsteffe** [comment]
Folowing test file before dragging, user.cfg and an additional image. The problem arise with a vertical drag of the highligted vertex. It happens also when I drag the other vertex belonging to the same horizontal edge. 
 
[planimetria_test.zip](https://github.com/realthunder/FreeCAD/files/14549013/planimetria_test.zip)
[user.zip](https://github.com/realthunder/FreeCAD/files/14549017/user.zip)

![Screenshot from 2024-03-10 06-31-07](https://github.com/realthunder/FreeCAD/assets/12879321/cb210a13-f2e1-4c0a-a5c7-9e93fdc8f38f)

**Comment by realthunder** [comment]
It is indeed caused by your settings. More specifically your sketcher solver setting as shown below. Mine is 100, which is the default value, I think.

![image](https://github.com/realthunder/FreeCAD/assets/1207888/7d491b0b-497f-4982-8cb2-a00feb4fede4)

**Comment by wsteffe** [comment]
Thanks for spotting the problem. 
But it is quite strange to me that a smaller number of solver iteration prevented dragging a vertex.
