### ISSUE TITLE
Shadow lighting direction is reset incorrectly

### ISSUE THREAD

**Issue by ftdt10** [realthunder/FreeCAD#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 2024.124.0.38947 (Git) Snap 127
Build type: Release
Branch: tag: 20240123stable
Hash: 0c0f69ad4806682096b51f7669d5f1cb83f9c7d7
Python 3.10.12, Qt 5.15.10, Coin 4.0.1rt, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Problem description

if setting is changed in DocumentRoot-ViewTab-Shadow, lighting direction resets incorrectly.
And if the document file is closed and reopened, the lighting direction is reset again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
Could you please provide some picture showing which parameters you've changed, and that changed before/after document reopened?

**Comment by ftdt10** [comment]
More detail steps to reproduce

1. run "menu-View-DrawStyle-Shadow", and run it again to show the directional light icon.
2. change the direction of light by dragging the arrow in 3d view
3. change "Light Intensity" parameter to other value, for example
then the direction of the light is reset
