### ISSUE TITLE
[Problem] No Stable 2024.03.17 build for macOS?

### ISSUE THREAD

**Issue by pgilfernandez** [realthunder/FreeCAD#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
The last stable release 2024.03.17 does not include a macOS build? was there any problem with it?

Thanks
```

### Subproject(s) affected?

None

### Problem description

Github last Stable 2024.03.17 release doesn't include any macOS build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by psommerfeld** [comment]
Also looking for MacOS (ideally M1) build.
I noticed with the previous release, the Mac assets were added day(s) later.

**Comment by pgilfernandez** [comment]
Maybe I wrote too soon then... let's wait then, thanks for the comment.

**Comment by oerkel47** [comment]
Linux Appimage is also still missing.

**Comment by psommerfeld** [comment]
Mac OS and Linux builds are now showing

**Comment by pgilfernandez** [comment]
Great, thanks for your comments
