### ISSUE TITLE
[Problem] 

### ISSUE THREAD

**Issue by julian-weinert** [realthunder/FreeCAD#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: macOS Mojave (10.14)
Word size of FreeCAD: 64-bit
Version: 2024.320.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240317stable)
Hash: 07c85fedeae51f76d1999f15b24d3c921f623f8d
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: C/Default (C)
Installed mods: 
  * ProDarkThemePreferencePack 1.0.0
  * freecad.gears 1.0.0
  * TabBar
  * library
  * CADExchanger
  * A2plus 0.4.60g
  * Manipulator 1.4.9
  * BIM 2021.12.0
  * kicadStepUpMod 10.16.8
  * fasteners 0.4.52
  * lattice2 1.0.0
  * Estimate 0.1.2
  * ExtremeProDark 2.6.4
  * Mechatronic
  * ToolbarStyle
  * ExplodedAssembly
  * Curves 0.6.5
  * Assembly4 0.12.5
  * Assembly3 0.11.4
```

### Subproject(s) affected?

PartDesign

### Problem description

I just installed the latest release and it breaks PartDesign completely.
When double clicking a body it goes into transform and there is no possibility to activate a body now.
This leads to FreeCAD to be completely broken and absolutely unusable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
Could you please post your file, or send to me by email?

**Comment by julian-weinert** [comment]
Thanks for getting back _this_ quickly. I'm so sorry, I had a complete brain fart moment and didn't realise that I actually opened an old file I had created with Part WB and not PartDesign. No idea why I didn't notice that in the tree view :/
I just spent 30 minutes with this...
