### ISSUE TITLE
Tiny area to switch between open files

### ISSUE THREAD

**Issue by sigxcpu76** [realthunder/FreeCAD#98]
Well, I've managed to reproduce this thing I've mentioned some time ago.
Sometimes, the area where you can click in the opened files toolbar is very narrow.
I've attached a clip that shows this behavior.

https://user-images.githubusercontent.com/737085/106679033-84be6e00-65c4-11eb-9ffb-61d76f658d4a.mp4

**Comment by realthunder** [comment]
Do you have any overlay dockable at the bottom?

**Comment by sigxcpu76** [comment]
They were all moved to the right.

![image](https://user-images.githubusercontent.com/737085/106681237-c7824500-65c8-11eb-8b77-d16a31ac1fce.png)

**Comment by luzpaz** [comment]
Can you still reproduce this @sigxcpu76

**Comment by sigxcpu76** [comment]
I didn't notice it for the past few versions so I guess it is fixed. Sorry for not coming back to this.
