### ISSUE TITLE
[Problem] Point constraints not being highlighted in Sketcher

### ISSUE THREAD

**Issue by butlerps** [realthunder/FreeCAD#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 12.7.3
Word size of FreeCAD: 64-bit
Version: 2024.407.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: C/Default (C)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Problem description

Brand new to FreeCAD, while in sketcher, when I click on a point constraint in the drawing area the item in the Tasks pane does not highlight which point has been selected.  Vice versa, if I select a contraint in the Tasks pane, the point in the drawing area does not turn green.  It does work when selecting lines (as shown first in the attached video).

https://github.com/realthunder/FreeCAD/assets/17883031/49d4df30-ee11-4aba-b792-af73efb5a8ae

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
The above commit fixes pre selection highlight when you hover mouse in constraint list in editing panel. To do the reverse, you can hover mouse in 3D view and press `G, G` to bring up the `Pick geometry` pie menu for disambiguation.


https://github.com/realthunder/FreeCAD/assets/1207888/4fb38ee2-9671-4843-81cb-86b60179c8d4
